emotions = {
    'anger': ['abandoned', 'abandonment', 'abhor', 'abhorrent', 'abolish', 'abomination', 'abuse', 'accursed',
              'accusation', 'accused', 'accuser', 'accusing', 'actionable', 'adder', 'adversary', 'adverse',
              'adversity', 'advocacy', 'affront', 'aftermath', 'aggravated', 'aggravating', 'aggravation', 'aggression',
              'aggressive', 'aggressor', 'agitated', 'agitation', 'agony', 'alcoholism', 'alienate', 'alienation',
              'allegation', 'altercation', 'ambush', 'anarchism', 'anarchist', 'anarchy', 'anathema', 'anger', 'angry',
              'anguish', 'animosity', 'animus', 'annihilate', 'annihilated', 'annihilation', 'annoy', 'annoyance',
              'annoying', 'antagonism', 'antagonist', 'antagonistic', 'antichrist', 'antipathy', 'antisocial',
              'antithesis', 'anxiety', 'argue', 'argument', 'argumentation', 'arguments', 'armament', 'armed',
              'arraignment', 'arrogant', 'arson', 'assail', 'assailant', 'assassin', 'assassinate', 'assassination',
              'assault', 'asshole', 'atrocious', 'atrocity', 'attack', 'attacking', 'attorney', 'avarice', 'avenger',
              'averse', 'aversion', 'awful', 'backbone', 'bad', 'badger', 'badness', 'bane', 'bang', 'banger', 'banish',
              'banished', 'banishment', 'bankruptcy', 'banshee', 'barb', 'barbaric', 'bark', 'barrier', 'bastion',
              'battalion', 'batter', 'battery', 'battle', 'battled', 'bayonet', 'bear', 'bearish', 'beast', 'beating',
              'bee', 'belittle', 'belligerent', 'bellows', 'belt', 'berserk', 'betray', 'betrayal', 'bias', 'bickering',
              'bigot', 'bigoted', 'bile', 'birch', 'birthplace', 'bitch', 'bitterly', 'bitterness', 'blackmail',
              'blame', 'blasphemous', 'blasphemy', 'blast', 'blatant', 'blaze', 'blemish', 'blockade', 'bloodshed',
              'bloodthirsty', 'bloody', 'bogus', 'boisterous', 'bomb', 'bombard', 'bombardment', 'bothering', 'bout',
              'boxing', 'brawl', 'brazen', 'brimstone', 'broil', 'broken', 'brunt', 'brutal', 'brutality', 'brute',
              'buffet', 'bugaboo', 'bully', 'bummer', 'burial', 'burke', 'busted', 'butcher', 'cacophony', 'cad',
              'callous', 'campaigning', 'cancer', 'cane', 'canker', 'cannon', 'carelessness', 'carnage', 'cash',
              'casualty', 'catastrophe', 'caution', 'celebrity', 'censor', 'chaff', 'challenge', 'chant', 'chaos',
              'chaotic', 'cheat', 'choke', 'claimant', 'clamor', 'clash', 'clashing', 'claw', 'coerce', 'coercion',
              'coldness', 'collision', 'collusion', 'combat', 'combatant', 'combative', 'commotion', 'communism',
              'complain', 'complaint', 'complicate', 'compress', 'compulsion', 'concealment', 'concussion', 'condemn',
              'condemnation', 'condescension', 'confine', 'confined', 'confinement', 'confiscate', 'conflagration',
              'conflict', 'confront', 'confusion', 'conquest', 'conspirator', 'consternation', 'constraint', 'contempt',
              'contemptible', 'contemptuous', 'contentious', 'contraband', 'contradict', 'controversial', 'convict',
              'coop', 'copycat', 'corrupting', 'counsellor', 'coup', 'court', 'crabby', 'cracked', 'cranky', 'crazed',
              'crazy', 'crime', 'criminal', 'criminality', 'criticism', 'criticize', 'cross', 'crucifixion', 'cruel',
              'cruelly', 'cruelty', 'crunch', 'crusade', 'crushed', 'crushing', 'cur', 'curse', 'cursed', 'cursing',
              'cussed', 'cutthroat', 'cutting', 'dabbling', 'daemon', 'damage', 'dame', 'damn', 'damnation', 'darkness',
              'dashed', 'dastardly', 'deadly', 'death', 'deceit', 'deceive', 'deceived', 'decry', 'defamatory',
              'defect', 'defendant', 'defense', 'defiance', 'defiant', 'deflate', 'defraud', 'defy', 'degeneracy',
              'delay', 'deleterious', 'delinquent', 'delusion', 'delusional', 'demand', 'demolish', 'demon', 'demonic',
              'denounce', 'denunciation', 'deny', 'deplorable', 'deplore', 'deportation', 'depraved', 'depravity',
              'depreciate', 'depreciated', 'depressed', 'deprivation', 'deranged', 'derision', 'derogation',
              'derogatory', 'desecration', 'desert', 'deserted', 'deserve', 'desist', 'despair', 'despicable',
              'despise', 'despotism', 'destroyed', 'destroyer', 'destroying', 'destruction', 'destructive', 'detainee',
              'deterioration', 'detest', 'detonation', 'detract', 'devastate', 'devastating', 'devastation', 'devil',
              'diabolical', 'diatribe', 'dictatorial', 'dictatorship', 'difficulty', 'disagree', 'disagreeing',
              'disagreement', 'disallowed', 'disappoint', 'disappointed', 'disapprove', 'disapproved', 'disapproving',
              'disaster', 'disastrous', 'disclaim', 'discontent', 'discord', 'discriminate', 'discrimination',
              'disdain', 'disease', 'disfigured', 'disgrace', 'disgraced', 'disgraceful', 'disgruntled', 'disgust',
              'disgusting', 'dishonest', 'dishonor', 'disillusionment', 'disinformation', 'dislike', 'disliked',
              'dislocated', 'dismay', 'dismissal', 'disobedience', 'disobedient', 'disobey', 'disparage', 'disparaging',
              'disparity', 'displaced', 'displeased', 'dispossessed', 'dispute', 'disqualified', 'disreputable',
              'disrespect', 'disrespectful', 'disruption', 'dissension', 'disservice', 'dissident', 'dissolution',
              'dissonance', 'distracted', 'distracting', 'distress', 'distressing', 'distrust', 'disturbance',
              'disturbed', 'disused', 'divorce', 'dominate', 'domination', 'doomsday', 'dreadful', 'duel', 'dumps',
              'dupe', 'duplicity', 'duress', 'dying', 'earthquake', 'effigy', 'egregious', 'elbow', 'elf',
              'elimination', 'encumbrance', 'endless', 'enemy', 'enforce', 'enmity', 'enslaved', 'entangled',
              'epidemic', 'eradicate', 'eradication', 'erupt', 'eruption', 'escalate', 'eschew', 'evade', 'eviction',
              'evil', 'exacerbation', 'exaggerate', 'exasperation', 'excitation', 'excite', 'execution', 'executioner',
              'exile', 'expel', 'expletive', 'explode', 'explosive', 'expulsion', 'extermination', 'extinguish',
              'failing', 'fallacious', 'falsehood', 'falsification', 'fatal', 'fear', 'fee', 'feeling', 'fenced',
              'ferocious', 'ferocity', 'fervor', 'feud', 'feudalism', 'fib', 'fiend', 'fierce', 'fight', 'fighting',
              'firearms', 'fits', 'flagrant', 'fleece', 'flog', 'fluctuation', 'foe', 'foray', 'forbidding', 'force',
              'forcibly', 'forearm', 'forfeit', 'forsaken', 'foul', 'fraud', 'fraudulent', 'frenetic', 'frenzied',
              'friction', 'frightful', 'frowning', 'frustrate', 'frustrated', 'frustration', 'fugitive', 'fuming',
              'furious', 'furiously', 'furnace', 'furor', 'fury', 'fuss', 'gall', 'gallows', 'gang', 'gent',
              'gibberish', 'glare', 'glaring', 'gnome', 'godless', 'gonorrhea', 'gore', 'gory', 'grab', 'grated',
              'grating', 'greed', 'grievance', 'grievous', 'grim', 'grope', 'growl', 'growling', 'grudge', 'gruff',
              'grumble', 'grumpy', 'guillotine', 'guilty', 'gun', 'halter', 'hamstring', 'hanging', 'harass',
              'harassing', 'harbinger', 'hardened', 'harmful', 'harry', 'harshness', 'hate', 'hateful', 'hating',
              'hatred', 'haughty', 'havoc', 'hell', 'hellish', 'hiss', 'hit', 'hoax', 'holocaust', 'homeless',
              'homicidal', 'homicide', 'honest', 'hood', 'hoot', 'hopelessness', 'horrible', 'horrid', 'horrific',
              'horror', 'hostage', 'hostile', 'hostilities', 'hostility', 'hot', 'howl', 'huff', 'humbug', 'humiliate',
              'hunting', 'hurt', 'hurtful', 'hurting', 'hysterical', 'idiocy', 'idiotic', 'ill', 'illegal',
              'illegality', 'illegitimate', 'illicit', 'immaturity', 'immoral', 'immorality', 'impermeable',
              'implicate', 'impotence', 'imprisoned', 'imprisonment', 'inadmissible', 'inappropriate', 'inattention',
              'incarceration', 'incase', 'incendiary', 'incense', 'incest', 'incite', 'incompatible', 'incompetent',
              'incongruous', 'inconsiderate', 'inconvenient', 'incredulous', 'incurable', 'indecency', 'indenture',
              'indict', 'indifference', 'indignant', 'indignation', 'indoctrination', 'inept', 'inequality',
              'inexcusable', 'infamous', 'infanticide', 'infantile', 'inferno', 'infidel', 'infidelity', 'inflict',
              'infraction', 'inhibit', 'inhuman', 'inimical', 'injure', 'injurious', 'injury', 'injustice',
              'inoperative', 'insane', 'insanity', 'insecure', 'insidious', 'insignificant', 'instinctive',
              'insufficiency', 'insult', 'insulting', 'insurrection', 'intense', 'interminable', 'interrupt',
              'intimidation', 'intolerable', 'intolerance', 'intolerant', 'intractable', 'intruder', 'intrusive',
              'invade', 'invader', 'invasion', 'involution', 'involvement', 'irate', 'ire', 'irreconcilable',
              'irritability', 'irritable', 'irritating', 'irritation', 'jab', 'jealous', 'jealousy', 'jeopardize',
              'jerk', 'kick', 'kicking', 'kidnap', 'killing', 'lace', 'lagging', 'lash', 'latent', 'lava',
              'lawlessness', 'lawsuit', 'lawyer', 'legalized', 'leukemia', 'libel', 'liberate', 'lie', 'lightning',
              'limited', 'liquor', 'litigate', 'litigious', 'livid', 'loath', 'loathe', 'loathsome', 'lonely', 'lose',
              'losing', 'loss', 'loudness', 'lunacy', 'lunatic', 'lying', 'lynch', 'mad', 'madden', 'madman', 'madness',
              'malevolent', 'malice', 'malicious', 'malign', 'malignant', 'malpractice', 'mangle', 'maniac',
              'manipulation', 'manslaughter', 'martial', 'masochism', 'massacre', 'mastery', 'meddle', 'melodrama',
              'menace', 'menacing', 'mighty', 'militia', 'misbehavior', 'misconception', 'miserable', 'misery',
              'mislead', 'misleading', 'misplace', 'misrepresented', 'misstatement', 'mistress', 'misunderstanding',
              'mob', 'mocking', 'molestation', 'money', 'monstrosity', 'moody', 'moral', 'morals', 'morbidity',
              'mortality', 'mosque', 'mosquito', 'mournful', 'muff', 'mug', 'mule', 'murder', 'murderer', 'murderous',
              'musical', 'mutilation', 'mutiny', 'mutter', 'myopia', 'nag', 'nasty', 'negation', 'neglected',
              'nepotism', 'nether', 'nettle', 'noisy', 'noncompliance', 'notoriety', 'nuisance', 'nurture', 'objection',
              'obliging', 'obliterate', 'obliterated', 'oblivion', 'obnoxious', 'obscenity', 'obstacle', 'obstruct',
              'obstructive', 'odious', 'offend', 'offended', 'offender', 'offense', 'offensive', 'onerous', 'opera',
              'opinionated', 'opium', 'opponent', 'opposed', 'opposition', 'oppress', 'oppression', 'oppressive',
              'oppressor', 'orc', 'orchestra', 'ordeal', 'oust', 'outburst', 'outcry', 'outrage', 'overbearing',
              'overpowering', 'overpriced', 'owing', 'painful', 'paralysis', 'paralyzed', 'pare', 'patter', 'paucity',
              'payback', 'penalty', 'penetration', 'penitentiary', 'perdition', 'pernicious', 'perpetrator',
              'persecute', 'persecution', 'perverse', 'perversion', 'pervert', 'pessimism', 'pest', 'phony', 'picket',
              'picketing', 'pillage', 'pique', 'pirate', 'pitfall', 'playful', 'plunder', 'poaching', 'poison',
              'poisoned', 'poisonous', 'polemic', 'politics', 'possessed', 'possession', 'pound', 'poverty', 'pow',
              'powerful', 'powerless', 'preclude', 'prejudice', 'prejudicial', 'presumptuous', 'pretending', 'prick',
              'prison', 'prisoner', 'profane', 'profanity', 'prohibited', 'prosecute', 'provocation', 'provoking',
              'pry', 'psychosis', 'punch', 'punished', 'punishing', 'punishment', 'punitive', 'quandary', 'quarrel',
              'rabble', 'rabid', 'rage', 'raging', 'raid', 'rail', 'ram', 'rampage', 'ransom', 'rape', 'rapping',
              'rascal', 'rating', 'rave', 'ravenous', 'raving', 'react', 'rebel', 'rebellion', 'recalcitrant',
              'recession', 'recidivism', 'reckless', 'recklessness', 'reject', 'rejection', 'rejects', 'remand',
              'remiss', 'remove', 'renegade', 'renounce', 'repay', 'repellent', 'reprimand', 'reprisal', 'reproach',
              'repudiation', 'resent', 'resentful', 'resentment', 'resign', 'resistance', 'resisting', 'restitution',
              'restrain', 'restriction', 'retaliate', 'retaliation', 'retaliatory', 'retract', 'retribution', 'revenge',
              'reversal', 'revoke', 'revolt', 'revolting', 'revolution', 'revolver', 'revulsion', 'rheumatism',
              'ribbon', 'ridicule', 'ridiculous', 'rifle', 'ringer', 'riot', 'riotous', 'rivalry', 'rob', 'robbery',
              'rocket', 'rook', 'row', 'ruined', 'ruinous', 'ruthless', 'saber', 'sabotage', 'saloon', 'sarcasm',
              'satanic', 'savage', 'savagery', 'scandalous', 'scapegoat', 'scar', 'scarcity', 'scare', 'schism',
              'schizophrenia', 'scoff', 'scold', 'scolding', 'scorching', 'scorn', 'scorpion', 'scoundrel', 'scourge',
              'scrapie', 'scream', 'screaming', 'screwed', 'sectarian', 'sedition', 'segregate', 'selfish', 'senseless',
              'sentence', 'separatist', 'shackle', 'shaky', 'sham', 'sharpen', 'shatter', 'shell', 'shit', 'shiver',
              'shock', 'shoddy', 'shoot', 'shooting', 'shoplifting', 'shortage', 'shot', 'shout', 'shove', 'shriek',
              'shrill', 'shun', 'sickening', 'simmer', 'sin', 'sinful', 'sinister', 'sinner', 'sisterhood', 'sizzle',
              'skewed', 'skid', 'skirmish', 'slam', 'slander', 'slap', 'slash', 'slaughter', 'slaughterhouse',
              'slaughtering', 'slave', 'slavery', 'slay', 'slayer', 'slur', 'slut', 'sly', 'smack', 'smash', 'smell',
              'smite', 'smother', 'smuggler', 'snarl', 'snarling', 'sneak', 'sneer', 'socialist', 'soldier', 'sordid',
              'sore', 'spank', 'spanking', 'spat', 'spear', 'spine', 'spite', 'spiteful', 'squelch', 'stab',
              'stalemate', 'standoff', 'standstill', 'steal', 'sterling', 'stifled', 'stigma', 'sting', 'stingy',
              'stolen', 'stone', 'storm', 'storming', 'strained', 'strangle', 'strife', 'strike', 'stripped',
              'struggle', 'subjugation', 'subsidy', 'subversion', 'subversive', 'sucker', 'sue', 'suffocation',
              'suicidal', 'suicide', 'sullen', 'suppress', 'suppression', 'supremacy', 'surcharge', 'surly',
              'suspicious', 'swastika', 'tackle', 'talons', 'tariff', 'taunt', 'tease', 'teasing', 'tempest', 'tension',
              'terrible', 'terrorism', 'terrorist', 'terrorize', 'theft', 'theocratic', 'thief', 'thoughtless',
              'thrash', 'threat', 'threaten', 'threatening', 'thresh', 'throttle', 'thug', 'thump', 'thundering',
              'tiff', 'tighten', 'tirade', 'tolerate', 'torment', 'torpedo', 'tortious', 'torture', 'touchy',
              'toughness', 'traitor', 'traumatic', 'treacherous', 'treachery', 'treason', 'treat', 'tree', 'tremor',
              'trespass', 'trickery', 'tripping', 'troll', 'troublesome', 'tumult', 'tumultuous', 'turbulence',
              'turmoil', 'tussle', 'tyrannical', 'tyrant', 'ulcer', 'ultimatum', 'unattainable', 'unbridled',
              'uncaring', 'uncertain', 'uncontrollable', 'underpaid', 'undesirable', 'unequal', 'unfair', 'unfairness',
              'unforgiving', 'unfriendly', 'unfulfilled', 'ungrateful', 'unhappy', 'unjust', 'unjustifiable', 'unkind',
              'unlawful', 'unlucky', 'unpaid', 'unruly', 'unsettled', 'unsympathetic', 'unthinkable', 'untoward',
              'untrustworthy', 'upheaval', 'uprising', 'upset', 'usurp', 'usurped', 'vampire', 'vehement', 'vendetta',
              'vengeance', 'vengeful', 'venom', 'venomous', 'vent', 'vermin', 'versus', 'veto', 'vicious', 'victim',
              'victimized', 'villainous', 'vindicate', 'vindictive', 'violation', 'violence', 'violent', 'violently',
              'virulence', 'volatility', 'vote', 'vulgarity', 'waffle', 'warden', 'warfare', 'warlike', 'warp',
              'warrior', 'wasted', 'wasteful', 'wench', 'whip', 'willful', 'wimpy', 'wince', 'wireless', 'witch',
              'witchcraft', 'wop', 'words', 'worthless', 'wound', 'wrangling', 'wrath', 'wreak', 'wreck', 'wrecked',
              'wretch', 'wring', 'wrongdoing', 'wrongful', 'wrongly', 'yell', 'yelp', 'youth'],
    'anticipation': ['abundance', 'accelerate', 'accolade', 'accompaniment', 'achievement', 'acquiring', 'addresses',
                     'adore', 'adrift', 'advance', 'advent', 'adventure', 'advocacy', 'airport', 'alertness', 'alerts',
                     'alive', 'allure', 'aloha', 'ambition', 'amour', 'analyst', 'angel', 'angling', 'announcement',
                     'anticipation', 'anticipatory', 'antidote', 'anxiety', 'anxious', 'appeal', 'applicant',
                     'apprehensive', 'approaching', 'arbitration', 'archaeology', 'ardent', 'arouse', 'arrival',
                     'arrive', 'art', 'aspiration', 'aspire', 'aspiring', 'astrologer', 'astronomer', 'atone',
                     'attainable', 'attempt', 'attendance', 'auction', 'audience', 'auspicious', 'await', 'award',
                     'ballot', 'balm', 'banger', 'banquet', 'basketball', 'beaming', 'begun', 'betrothed', 'beware',
                     'biennial', 'birth', 'birthday', 'bless', 'blessing', 'blessings', 'blindfold', 'bloom', 'board',
                     'boisterous', 'bonus', 'boomerang', 'bountiful', 'bounty', 'bridal', 'bride', 'bridegroom',
                     'brilliant', 'broadside', 'brotherly', 'bruise', 'buddy', 'bugle', 'buzz', 'bye', 'calculation',
                     'calls', 'candid', 'cap', 'captivate', 'career', 'cash', 'cataract', 'caution', 'cautious',
                     'celebrated', 'celebrating', 'celebration', 'celebrity', 'celestial', 'cement', 'champion',
                     'changeable', 'chant', 'charitable', 'chastity', 'cheer', 'cheerfulness', 'cheery', 'cherish',
                     'chicane', 'child', 'chocolate', 'chuckle', 'church', 'clamor', 'clap', 'climax', 'clock',
                     'closure', 'clown', 'clue', 'comfort', 'coming', 'commemorate', 'commemoration', 'commemorative',
                     'commonplace', 'compensate', 'competition', 'complement', 'completing', 'completion', 'compliment',
                     'concealed', 'concealment', 'condemnation', 'confession', 'conjecture', 'conjure', 'consecration',
                     'consequent', 'conservation', 'conspirator', 'contagion', 'contingent', 'continuation', 'continue',
                     'convergence', 'convince', 'correspondence', 'council', 'countdown', 'court', 'courtship', 'cove',
                     'cradle', 'cramp', 'craps', 'crave', 'craving', 'cream', 'creeping', 'crescendo', 'crowning',
                     'cue', 'cultivate', 'curiosity', 'daily', 'dare', 'dawn', 'deal', 'death', 'debenture', 'defense',
                     'delight', 'delighted', 'delightful', 'deliverance', 'delivery', 'denying', 'depart', 'depend',
                     'depraved', 'deserve', 'destination', 'destined', 'detainee', 'determinate', 'develop', 'devil',
                     'devout', 'diagnosis', 'dictatorship', 'dietary', 'digress', 'diplomacy', 'discreet', 'discretion',
                     'dismay', 'disposed', 'distracting', 'divination', 'doomsday', 'dove', 'draft', 'dread',
                     'dreadful', 'duel', 'dutiful', 'eager', 'eagerness', 'ecstasy', 'ecstatic', 'edification',
                     'edition', 'efficient', 'ejaculation', 'elegance', 'elevation', 'elite', 'emancipation', 'embrace',
                     'enchant', 'enchanting', 'endanger', 'endeavor', 'engaged', 'engulf', 'enjoy', 'enjoying',
                     'enroll', 'entertaining', 'entertainment', 'enthusiasm', 'enthusiast', 'epidemic', 'erotic',
                     'errand', 'escape', 'eventual', 'eventuality', 'exalt', 'excavation', 'exceed', 'excel',
                     'excitation', 'excite', 'excited', 'excitement', 'exciting', 'exhaustion', 'exigent', 'expect',
                     'expectancy', 'expectant', 'expectation', 'expected', 'expecting', 'expedition', 'experiment',
                     'explore', 'explosive', 'expose', 'extricate', 'failing', 'fain', 'faith', 'familiarity', 'fancy',
                     'fanfare', 'farm', 'fate', 'favorable', 'feat', 'feeling', 'ferment', 'fermentation', 'festival',
                     'fete', 'fiesta', 'finally', 'firstborn', 'fitting', 'flinch', 'flirt', 'football', 'forearm',
                     'foreboding', 'forecast', 'foresee', 'foreseen', 'foresight', 'forewarned', 'forming', 'fortune',
                     'frantic', 'friendly', 'frisky', 'fulfillment', 'fun', 'gain', 'gambler', 'gambling', 'generosity',
                     'germ', 'germination', 'gift', 'glad', 'glide', 'glimmer', 'glorify', 'glory', 'glow', 'god',
                     'good', 'goodness', 'gradual', 'graduation', 'grandchildren', 'grant', 'grasping', 'gravitate',
                     'grim', 'grin', 'grow', 'guillotine', 'habitual', 'hankering', 'hap', 'happen', 'happiness',
                     'happy', 'harbinger', 'harvest', 'haste', 'headlight', 'healing', 'heavenly', 'heft', 'hero',
                     'heroism', 'heyday', 'highest', 'hire', 'holiday', 'holiness', 'homeless', 'honeymoon', 'hope',
                     'hopeful', 'horizon', 'horoscope', 'humanitarian', 'hungry', 'hunter', 'hunting', 'hurried',
                     'hurry', 'hymn', 'hype', 'hypothesis', 'illuminate', 'immature', 'immaturity', 'immediately',
                     'immerse', 'imminent', 'immortality', 'impatient', 'impending', 'importance', 'improve',
                     'improvise', 'inaugural', 'inauguration', 'incite', 'income', 'independence', 'infant',
                     'infanticide', 'infinity', 'inheritance', 'inoculation', 'inquiry', 'inspiration', 'inspire',
                     'install', 'instructions', 'instructor', 'intended', 'interim', 'interminable', 'intermission',
                     'intimate', 'intimately', 'intrigue', 'intuitively', 'investigation', 'invitation', 'invite',
                     'inviting', 'invocation', 'invoke', 'jackpot', 'jeopardy', 'journey', 'judicial', 'judiciary',
                     'kindred', 'kiss', 'labor', 'labyrinth', 'lagging', 'latent', 'laughter', 'launch', 'leisure',
                     'lessen', 'lesson', 'letter', 'lettered', 'liberate', 'liberation', 'liberty', 'linger',
                     'litigate', 'localize', 'long', 'longing', 'loom', 'lottery', 'lovely', 'lover', 'luck', 'lull',
                     'luscious', 'lust', 'magical', 'magnificence', 'magnificent', 'mail', 'majestic', 'marriage',
                     'marry', 'matchmaker', 'maternal', 'matrimony', 'medal', 'mediate', 'mediator', 'medical',
                     'meditate', 'merge', 'midwife', 'mill', 'miracle', 'mobile', 'momentum', 'monetary', 'money',
                     'morals', 'morn', 'morrow', 'mortification', 'mother', 'motion', 'mountain', 'musical', 'mutable',
                     'mysterious', 'mystery', 'nascent', 'navigable', 'navigator', 'neighbor', 'neighborhood',
                     'nervous', 'network', 'neutral', 'nobility', 'noncompliance', 'notification', 'nurture', 'oasis',
                     'objective', 'obliging', 'offset', 'olfactory', 'omen', 'ominous', 'ongoing', 'onset', 'opera',
                     'opponent', 'opportunity', 'optimism', 'oracle', 'ordination', 'organ', 'organization', 'orgasm',
                     'outdo', 'overdue', 'overthrow', 'overture', 'owing', 'paddle', 'parade', 'paragon', 'paralysis',
                     'pare', 'parole', 'passenger', 'passion', 'passionate', 'patience', 'patient', 'pay', 'peace',
                     'peaceful', 'perfect', 'perfection', 'peril', 'perilous', 'perpetuate', 'perpetuity', 'picket',
                     'picnic', 'plan', 'planning', 'playground', 'plea', 'pleasant', 'plight', 'plump', 'poke',
                     'possess', 'possibility', 'powerful', 'practise', 'praiseworthy', 'pray', 'precarious', 'precious',
                     'precursor', 'predict', 'prediction', 'predilection', 'predispose', 'preliminary', 'preparation',
                     'preparatory', 'prepare', 'prepared', 'preparedness', 'prerequisite', 'prescient', 'present',
                     'preservative', 'pretty', 'prevail', 'prevention', 'priesthood', 'princely', 'probability',
                     'probation', 'proceeding', 'production', 'proficiency', 'prognosis', 'prognostic', 'progress',
                     'progression', 'prologue', 'prophecy', 'prophet', 'prophetic', 'prophylactic', 'prospectively',
                     'prosper', 'proud', 'providing', 'pry', 'public', 'punctual', 'punished', 'punt', 'puppy', 'quest',
                     'quicken', 'quote', 'rabid', 'radiance', 'raffle', 'rail', 'ram', 'rapture', 'raving', 'readiness',
                     'ready', 'receiving', 'recipient', 'recognizable', 'recombination', 'reconciliation',
                     'reconstruct', 'reconstruction', 'recreation', 'recreational', 'recurrent', 'regatta',
                     'regularity', 'rehabilitation', 'rejoice', 'rejoicing', 'rekindle', 'remedy', 'renovate',
                     'renovation', 'repay', 'representing', 'rescue', 'respect', 'responsive', 'restlessness',
                     'restorative', 'result', 'resultant', 'retirement', 'reunion', 'revenge', 'revere', 'revival',
                     'revive', 'revolution', 'reward', 'ribbon', 'ripen', 'rising', 'risk', 'risky', 'romance',
                     'romantic', 'roulette', 'saint', 'saintly', 'salary', 'saliva', 'salvation', 'sanctify',
                     'sanctuary', 'savor', 'scare', 'scientist', 'score', 'scrutinize', 'secular', 'seductive', 'seek',
                     'sensual', 'sensuality', 'sentence', 'sequel', 'serenity', 'serial', 'sex', 'shackle', 'shaky',
                     'share', 'sharpen', 'shining', 'ship', 'shiver', 'shopping', 'shortly', 'signify', 'simmer',
                     'simmering', 'simplify', 'sing', 'skewed', 'sneaking', 'sonar', 'sorcery', 'soundness', 'spa',
                     'sparkle', 'spear', 'spectacular', 'speculative', 'spirits', 'splendor', 'star', 'starry', 'start',
                     'stealthy', 'sterling', 'store', 'strategist', 'stripped', 'strive', 'submit', 'subscribe',
                     'succeed', 'succeeding', 'success', 'successful', 'sun', 'sundial', 'sunny', 'sunset',
                     'superstitious', 'supremacy', 'surprisingly', 'surround', 'suspense', 'suspicious', 'sweet',
                     'sweetheart', 'sweets', 'swim', 'symphony', 'synchronize', 'tabulate', 'tantalizing', 'tease',
                     'tempest', 'testament', 'theology', 'theory', 'thermocouple', 'thirst', 'thought', 'threaten',
                     'thrill', 'thrilling', 'thriving', 'tickle', 'time', 'timidity', 'tomorrow', 'top', 'torture',
                     'towering', 'track', 'transcendence', 'transitional', 'treadmill', 'treasure', 'treat', 'tree',
                     'tremor', 'trepidation', 'tribunal', 'tributary', 'triumph', 'triumphant', 'trophy', 'twinkle',
                     'ultimate', 'ultimately', 'unaccountable', 'unbeaten', 'unbridled', 'uncontrollable', 'undecided',
                     'undertaking', 'undisclosed', 'undoubted', 'undying', 'uneasiness', 'unexpected', 'unexplained',
                     'unfold', 'unfulfilled', 'unification', 'university', 'unknown', 'unpublished', 'unresolved',
                     'unsurpassed', 'untold', 'unverified', 'uphill', 'uplift', 'uprising', 'urgency', 'urgent',
                     'utopian', 'vacation', 'venerable', 'veracity', 'verge', 'victory', 'vigil', 'vigilance',
                     'vindication', 'virginity', 'vision', 'visionary', 'visitor', 'visor', 'volatility', 'volunteer',
                     'voluptuous', 'vote', 'vow', 'voyage', 'wait', 'warn', 'warned', 'watch', 'weigh', 'weight',
                     'whim', 'white', 'wilderness', 'winner', 'winning', 'winnings', 'wireless', 'wishful', 'withstand',
                     'wizard', 'wont', 'worm', 'worry', 'worrying', 'worship', 'yearning', 'young', 'youth', 'zeal',
                     'zest'],
    'disgust': ['aberration', 'abhor', 'abhorrent', 'abject', 'abnormal', 'abominable', 'abomination', 'abortion',
                'abundance', 'abuse', 'accusation', 'actionable', 'adder', 'adultery', 'adverse', 'affliction',
                'affront', 'aftermath', 'aggravation', 'aghast', 'airs', 'alcoholism', 'alien', 'alienate',
                'alienation', 'ammonia', 'amphetamines', 'anaconda', 'anathema', 'angry', 'animosity', 'annoy',
                'annoyance', 'antagonistic', 'anthrax', 'antichrist', 'antipathy', 'antisocial', 'aphid', 'appalling',
                'arrogant', 'arsenic', 'ashamed', 'asshole', 'asymmetry', 'atrocious', 'atrocity', 'atrophy',
                'attacking', 'autopsy', 'avarice', 'averse', 'aversion', 'awful', 'awkwardness', 'baboon', 'backwards',
                'bacteria', 'bacterium', 'bad', 'badness', 'bane', 'bang', 'banish', 'banishment', 'bankruptcy',
                'banshee', 'barbaric', 'barf', 'barrow', 'bastard', 'beastly', 'belittle', 'bestial', 'betray',
                'betrayal', 'bickering', 'bigot', 'bigoted', 'bile', 'birch', 'bitch', 'bitterly', 'bitterness',
                'blame', 'blasphemous', 'blatant', 'bleeding', 'blemish', 'blight', 'blighted', 'blister', 'bloated',
                'blob', 'bloodshed', 'bloodthirsty', 'bloody', 'blunder', 'bogus', 'boil', 'bombed', 'bovine', 'bowels',
                'boy', 'bran', 'brawl', 'bribery', 'brothel', 'bug', 'bum', 'bummer', 'bureaucrat', 'burglar', 'burke',
                'burnt', 'butcher', 'cacophony', 'cad', 'cadaver', 'callous', 'cancer', 'canker', 'cannibal',
                'cannibalism', 'carcass', 'carelessness', 'caries', 'carnage', 'catastrophe', 'catechism', 'celebrity',
                'censor', 'cess', 'chagrin', 'cheat', 'cholera', 'claimant', 'clamor', 'clumsy', 'coerce', 'coercion',
                'coldness', 'collapse', 'collusion', 'compost', 'condemnation', 'condescension', 'confined', 'congress',
                'conspirator', 'constipation', 'contagion', 'contagious', 'contaminate', 'contaminated',
                'contamination', 'contempt', 'contemptible', 'contentious', 'contraband', 'convict', 'coop', 'copycat',
                'corpse', 'corrupting', 'corruption', 'cough', 'cove', 'coward', 'crap', 'crawl', 'creature',
                'criminal', 'criminality', 'cringe', 'criticize', 'critter', 'crucifixion', 'crude', 'cruel', 'cruelty',
                'crushed', 'crushing', 'crusty', 'cuckold', 'cupping', 'cur', 'curse', 'cursing', 'cutting', 'cystic',
                'dabbling', 'daemon', 'daft', 'damage', 'dame', 'damn', 'dandy', 'dank', 'dastardly', 'deadly', 'death',
                'debauchery', 'debris', 'decayed', 'deceit', 'deceitful', 'deceive', 'decompose', 'decomposition',
                'defamation', 'default', 'defective', 'defiance', 'deform', 'deformed', 'deformity', 'defraud',
                'degeneracy', 'degrade', 'degrading', 'delay', 'deleterious', 'delinquent', 'delirium', 'demon',
                'demonic', 'denounce', 'denunciation', 'deplorable', 'deplore', 'depraved', 'depravity', 'depreciate',
                'depreciated', 'depressing', 'deprivation', 'deranged', 'derision', 'derogation', 'derogatory',
                'desecration', 'desert', 'deserted', 'desist', 'despair', 'despicable', 'despise', 'despotism',
                'destructive', 'deteriorated', 'deterioration', 'detest', 'devastating', 'devil', 'devilish',
                'diabolical', 'diaper', 'diarrhoea', 'diatribe', 'dictatorship', 'dilapidated', 'dire', 'dirt', 'dirty',
                'disallowed', 'disappoint', 'disappointed', 'disappointment', 'disapprove', 'disapproving', 'disaster',
                'disclaim', 'discoloration', 'discolored', 'discontent', 'discontinuity', 'discord', 'discriminating',
                'discrimination', 'disdain', 'disease', 'diseased', 'disfigured', 'disgrace', 'disgraced',
                'disgraceful', 'disgruntled', 'disgust', 'disgusting', 'dishonest', 'dishonesty', 'dishonor',
                'disillusionment', 'disingenuous', 'disintegrate', 'dislike', 'dislocated', 'dismal', 'dismemberment',
                'dismissal', 'disobedience', 'disobey', 'disparage', 'disparaging', 'disparity', 'displeased',
                'displeasure', 'dispose', 'disqualified', 'disregarded', 'disreputable', 'disrespectful', 'dissection',
                'disservice', 'distaste', 'distasteful', 'distorted', 'distress', 'distrust', 'divorce', 'donkey',
                'doomsday', 'dreadful', 'dreadfully', 'drivel', 'drool', 'drunken', 'dung', 'duress', 'dying',
                'dysentery', 'egotistical', 'egregious', 'elf', 'elimination', 'endemic', 'enema', 'enemy', 'enslaved',
                'entangled', 'entrails', 'epidemic', 'eradication', 'evade', 'eviction', 'evil', 'exasperation',
                'excellence', 'excluded', 'exclusion', 'excrement', 'excretion', 'exigent', 'expel', 'expulsion',
                'faeces', 'failure', 'falsify', 'falsity', 'farcical', 'fat', 'fatty', 'fecal', 'feces', 'feeling',
                'ferocious', 'fiend', 'fierce', 'filth', 'filthy', 'finally', 'flabby', 'flagrant', 'flatulence',
                'flea', 'fleece', 'flesh', 'flinch', 'flog', 'flop', 'fool', 'foul', 'frantic', 'fraudulent',
                'freakish', 'frowning', 'frustrate', 'fugitive', 'fungus', 'furious', 'fussy', 'gaby', 'gag', 'gall',
                'garbage', 'garish', 'gelatin', 'gent', 'germ', 'ghastly', 'ghetto', 'glitter', 'glut', 'gluttony',
                'gnome', 'gob', 'goblin', 'gonorrhea', 'goo', 'gore', 'gorge', 'gory', 'grating', 'gratuitous', 'gray',
                'greasy', 'greed', 'greedy', 'grievance', 'grim', 'grime', 'grimy', 'grisly', 'groan', 'grope', 'gross',
                'grotesque', 'growling', 'gruesome', 'gruff', 'grumble', 'grumpy', 'guillotine', 'guilt', 'gush', 'gut',
                'gutter', 'hag', 'hairy', 'hanging', 'harass', 'hardened', 'harlot', 'harmful', 'hate', 'hateful',
                'hatred', 'heartworm', 'hell', 'hellish', 'hemorrhage', 'heretic', 'herpes', 'herpesvirus', 'hideous',
                'hoax', 'hog', 'holocaust', 'homeless', 'homicide', 'honest', 'hood', 'hoot', 'hopelessness',
                'horrible', 'horrid', 'horrific', 'horrifying', 'horror', 'hostile', 'hostility', 'howl', 'huff',
                'hulk', 'humble', 'humbug', 'humiliating', 'humiliation', 'hurtful', 'hydrocephalus', 'hypertrophy',
                'hypocrite', 'hypocritical', 'idiocy', 'idiot', 'idiotic', 'idolatry', 'ignorant', 'ill', 'illegal',
                'illegality', 'illegitimate', 'illicit', 'illiterate', 'immoral', 'immorality', 'impeach', 'impolite',
                'imprisoned', 'imprisonment', 'impure', 'impurity', 'inadmissible', 'inappropriate', 'incarceration',
                'incase', 'incest', 'incestuous', 'incompatible', 'inconsiderate', 'inconvenient', 'incredulous',
                'incubus', 'incurable', 'indecency', 'indecent', 'indifference', 'indignation', 'ineffectual',
                'inefficiency', 'inept', 'ineptitude', 'inexcusable', 'infamous', 'infanticide', 'infantile', 'infect',
                'infectious', 'infestation', 'infidel', 'infidelity', 'inhibit', 'inhuman', 'iniquity', 'inmate',
                'insanity', 'insidious', 'instability', 'instinctive', 'insult', 'insulting', 'intense', 'interested',
                'interior', 'intestinal', 'intolerance', 'intolerant', 'intoxicated', 'intrusive', 'irrational',
                'irritating', 'irritation', 'janitor', 'jealous', 'jealousy', 'john', 'kite', 'lagging', 'lament',
                'larceny', 'larger', 'latent', 'latrines', 'laughable', 'lavatory', 'lawsuit', 'lawyer', 'laxative',
                'leeches', 'leer', 'lemon', 'leprosy', 'lesbian', 'lesser', 'lethal', 'lewd', 'liar', 'lick', 'lie',
                'litigate', 'litigious', 'livid', 'loathe', 'loathing', 'loathsome', 'lonely', 'loo', 'loon', 'lord',
                'lose', 'louse', 'lumpy', 'lunacy', 'lunatic', 'lurid', 'lush', 'lusty', 'lying', 'lynch', 'mad',
                'maggot', 'malaria', 'malevolent', 'malfeasance', 'malicious', 'malign', 'mange', 'mangle',
                'manslaughter', 'manure', 'masochism', 'massacre', 'materialist', 'measles', 'mess', 'messy', 'mildew',
                'mire', 'misbehavior', 'misconception', 'misconduct', 'miserable', 'misery', 'misguided', 'mishap',
                'misleading', 'misplace', 'misstatement', 'mistress', 'mistrust', 'mite', 'mockery', 'mocking',
                'molestation', 'monochrome', 'monstrosity', 'morals', 'morbidity', 'morgue', 'mortification',
                'mosquito', 'mouthful', 'muck', 'mucous', 'mucus', 'muddy', 'muff', 'murder', 'murderer', 'murderous',
                'murky', 'musty', 'mutilated', 'mutilation', 'mutiny', 'nameless', 'nappy', 'nasty', 'nausea',
                'nauseous', 'nefarious', 'neglected', 'nepotism', 'nettle', 'neurotic', 'nicotine', 'nose', 'notoriety',
                'noxious', 'nurture', 'obese', 'obesity', 'obi', 'obliging', 'obnoxious', 'obscene', 'obscenity',
                'occult', 'octopus', 'oddity', 'odious', 'offend', 'offender', 'offense', 'offensive', 'ogre', 'ooze',
                'opium', 'opponent', 'oppress', 'oppression', 'oppressive', 'orc', 'outcast', 'outhouse', 'outrage',
                'overpriced', 'owing', 'painful', 'palsy', 'parasite', 'parrot', 'pathetic', 'paucity', 'perdition',
                'perpetrator', 'persecution', 'perspiration', 'perverse', 'perversion', 'pervert', 'perverted', 'pest',
                'pestilence', 'petroleum', 'phlegm', 'phony', 'pig', 'piles', 'pillage', 'pimple', 'pious', 'pitfall',
                'plagiarism', 'plague', 'plight', 'plunder', 'poaching', 'poison', 'poisoned', 'poisoning', 'poisonous',
                'polemic', 'politic', 'pollute', 'pollution', 'polygamy', 'pompous', 'porn', 'pornography', 'possessed',
                'possession', 'poverty', 'powerful', 'powerless', 'pregnancy', 'prejudiced', 'presumptuous', 'prick',
                'prisoner', 'prohibited', 'prolong', 'prosecution', 'prostitute', 'prostitution', 'provoking', 'puke',
                'pungent', 'punished', 'punishment', 'purgatory', 'pus', 'quack', 'quagmire', 'questionable', 'rabid',
                'raging', 'rags', 'rancid', 'rape', 'rascal', 'rash', 'rat', 'rave', 'rebellion', 'recalcitrant',
                'recession', 'recidivism', 'recklessness', 'reflux', 'regurgitation', 'rejection', 'remains', 'remiss',
                'repellant', 'repellent', 'repelling', 'reproach', 'repudiation', 'repulsion', 'resentment', 'resign',
                'retard', 'reversal', 'revoke', 'revolting', 'revulsion', 'ridicule', 'ridiculous', 'rigor', 'rob',
                'robber', 'robbery', 'rogue', 'rook', 'rot', 'rotting', 'rubbish', 'ruined', 'ruinous', 'ruthless',
                'sabotage', 'sacrifices', 'sarcasm', 'saturated', 'savor', 'scar', 'schizophrenia', 'scoff', 'scold',
                'scorpion', 'scoundrel', 'scream', 'screaming', 'scrub', 'scum', 'secrete', 'secretion', 'segregate',
                'selfish', 'senseless', 'sentence', 'separatist', 'septic', 'serpent', 'servile', 'sewage', 'sewer',
                'sewerage', 'shabby', 'shack', 'shackle', 'sham', 'shame', 'shameless', 'shanghai', 'shit', 'shoddy',
                'shoplifting', 'shun', 'sick', 'sickening', 'sickly', 'sickness', 'sin', 'sinful', 'sinister', 'sinner',
                'sinning', 'slander', 'slaughter', 'slaughterhouse', 'slaughtering', 'slavery', 'slayer', 'slime',
                'slimy', 'slop', 'sloppy', 'sloth', 'sludge', 'slug', 'slum', 'slur', 'slush', 'slut', 'sly', 'smell',
                'smelling', 'smuggler', 'smut', 'snake', 'snarl', 'sneer', 'sneeze', 'socialism', 'socialist', 'soil',
                'soiled', 'soot', 'sordid', 'soreness', 'soulless', 'sour', 'speck', 'spew', 'spider', 'spit', 'spoil',
                'spurious', 'squeamish', 'squelch', 'squirm', 'stain', 'stalemate', 'stall', 'stealing', 'sticky',
                'stigma', 'stingy', 'stink', 'stinking', 'stomach', 'stools', 'strangle', 'stripped', 'sty',
                'subjugation', 'subsidy', 'subvert', 'suffering', 'suffocating', 'suicidal', 'sump', 'sunk',
                'suppression', 'surly', 'swamp', 'swampy', 'swarm', 'swig', 'swine', 'taboo', 'tariff', 'tarnish',
                'tasteless', 'tawny', 'tearful', 'teeming', 'termite', 'terrible', 'terrorism', 'terrorist', 'tetanus',
                'theft', 'theism', 'thief', 'thoughtless', 'thrash', 'threatening', 'thrift', 'thug', 'tirade', 'toad',
                'toilet', 'tortious', 'torture', 'toxic', 'traitor', 'tramp', 'trash', 'trashy', 'travesty',
                'treacherous', 'treason', 'treat', 'tree', 'tribunal', 'trickery', 'tyrannical', 'tyrant', 'ugliness',
                'ugly', 'ulcer', 'unaccountable', 'unattractive', 'unbearable', 'uncaring', 'uncertain', 'unclean',
                'unconscionable', 'undesirable', 'undoubted', 'uneasy', 'unequal', 'unfair', 'unfaithful',
                'unfavorable', 'unfriendly', 'ungrateful', 'unhappy', 'unhealthy', 'unjustifiable', 'unkind',
                'unlawful', 'unlucky', 'unmanageable', 'unnatural', 'unpleasant', 'unpopular', 'unruly',
                'unsatisfactory', 'unsatisfied', 'unsettled', 'unsightly', 'unthinkable', 'untidy', 'untoward',
                'unwashed', 'unworthy', 'vacuous', 'vainly', 'vampire', 'varicella', 'vegetative', 'venom', 'venomous',
                'vermin', 'vesicular', 'vicious', 'victimized', 'villainous', 'vindictive', 'violent', 'violently',
                'vomit', 'vulgar', 'vulgarity', 'vulture', 'wallow', 'wart', 'waste', 'wasted', 'wasteful', 'wasting',
                'weight', 'weird', 'wench', 'whine', 'whore', 'wickedness', 'wimp', 'wimpy', 'wince', 'winning',
                'witch', 'withered', 'woe', 'woefully', 'worsening', 'worthless', 'wrangling', 'wreck', 'wretch',
                'wretched', 'wrongdoing', 'wrongful'],
    'fear': ['abandon', 'abandoned', 'abandonment', 'abduction', 'abhor', 'abhorrent', 'abominable', 'abomination',
             'abortion', 'absence', 'abuse', 'abyss', 'accident', 'accidental', 'accursed', 'accused', 'accuser',
             'accusing', 'acrobat', 'adder', 'adjudicate', 'admonition', 'adrift', 'advance', 'adverse', 'adversity',
             'afflict', 'affliction', 'affront', 'afraid', 'aftermath', 'aga', 'aggression', 'aggressive', 'aggressor',
             'aghast', 'agonizing', 'agony', 'ailing', 'alarm', 'alarming', 'alcoholism', 'alertness', 'alerts',
             'alien', 'alienation', 'ambulance', 'ambush', 'anaconda', 'anarchism', 'anarchist', 'anarchy', 'anathema',
             'angina', 'anguish', 'animosity', 'annihilate', 'annihilated', 'annihilation', 'anomaly', 'anthrax',
             'antichrist', 'antisocial', 'anxiety', 'anxious', 'apache', 'appalling', 'apparition', 'appendicitis',
             'apprehend', 'apprehension', 'apprehensive', 'armament', 'armaments', 'armed', 'armor', 'armored',
             'arraignment', 'arsenic', 'arson', 'artillery', 'asp', 'assail', 'assailant', 'assassin', 'assassinate',
             'assassination', 'assault', 'astray', 'asylum', 'atherosclerosis', 'atrocity', 'atrophy', 'attack',
             'attacking', 'attorney', 'auditor', 'austere', 'autopsy', 'avalanche', 'averse', 'aversion', 'avoid',
             'avoidance', 'avoiding', 'awful', 'bacteria', 'bacterium', 'bad', 'badness', 'bailiff', 'bait', 'bale',
             'bane', 'bang', 'banger', 'banish', 'banished', 'bankrupt', 'bankruptcy', 'banshee', 'barbarian',
             'barbaric', 'barricade', 'batter', 'battered', 'battled', 'battlefield', 'bayonet', 'bear', 'bearish',
             'beast', 'beastly', 'beating', 'bee', 'behemoth', 'belittle', 'belligerent', 'belt', 'bestial', 'beware',
             'bewildered', 'bewilderment', 'bier', 'bigot', 'bigoted', 'biopsy', 'birch', 'birth', 'bitch', 'blackmail',
             'blackness', 'blast', 'bleeding', 'blemish', 'blight', 'blindfold', 'blob', 'blockade', 'bloodshed',
             'bloodthirsty', 'bloody', 'blues', 'bomb', 'bombard', 'bombardment', 'bomber', 'bondage', 'bottomless',
             'brawl', 'brigade', 'brimstone', 'broke', 'broken', 'brutal', 'brutality', 'brute', 'buck', 'bug',
             'bugaboo', 'bully', 'bunker', 'burdensome', 'burglar', 'burial', 'buried', 'burke', 'busted', 'butcher',
             'buzz', 'cabal', 'cadaver', 'campaigning', 'cancer', 'cane', 'cannibal', 'cannon', 'captive', 'captor',
             'carcass', 'carcinoma', 'cardiomyopathy', 'carnage', 'carnivorous', 'cartridge', 'case', 'cash', 'casket',
             'casualty', 'cataract', 'catastrophe', 'caution', 'cautionary', 'cautious', 'cautiously', 'cemetery',
             'censor', 'chaff', 'challenge', 'change', 'chaos', 'chargeable', 'chasm', 'chicken', 'chimera', 'cholera',
             'clashing', 'claw', 'cleave', 'cliff', 'cloudiness', 'cobra', 'coerce', 'coercion', 'coffin', 'coldness',
             'collapse', 'collusion', 'coma', 'comatose', 'combat', 'combatant', 'combative', 'communism', 'compassion',
             'concealed', 'concealment', 'concerned', 'condemnation', 'confession', 'confessional', 'confidence',
             'confine', 'confined', 'confinement', 'conflagration', 'conflict', 'confusion', 'conquest', 'conspiracy',
             'conspirator', 'conspire', 'consternation', 'constrain', 'constraint', 'contagion', 'contagious',
             'contaminated', 'contempt', 'contentious', 'contraband', 'convict', 'cop', 'corrosive', 'corrupting',
             'counsellor', 'courageous', 'court', 'cove', 'coward', 'cowardice', 'cowardly', 'coy', 'coyote', 'cracked',
             'crash', 'crazed', 'crazy', 'creature', 'criminal', 'criminality', 'cringe', 'cripple', 'criticize',
             'crocodile', 'cross', 'crouch', 'crouching', 'crucifixion', 'cruel', 'cruelly', 'cruelty', 'crusade',
             'crushed', 'crushing', 'crypt', 'cult', 'cupping', 'cur', 'curse', 'cursed', 'cutter', 'cutthroat',
             'cutting', 'cyanide', 'cyclone', 'cyst', 'daemon', 'dagger', 'damnation', 'danger', 'dangerous', 'darken',
             'darkened', 'darkness', 'dart', 'dashed', 'dastardly', 'deadly', 'death', 'debacle', 'debauchery', 'decay',
             'deceit', 'decomposition', 'defamation', 'default', 'defection', 'defend', 'defendant', 'defense',
             'defenseless', 'defiance', 'deflation', 'deformity', 'defy', 'degrading', 'delay', 'deleterious', 'deluge',
             'delusion', 'delusional', 'demented', 'dementia', 'demise', 'demon', 'demonic', 'demoralized', 'dentistry',
             'denunciation', 'dependence', 'deplorable', 'deport', 'deportation', 'depraved', 'depreciated',
             'depreciation', 'depress', 'depressed', 'deprivation', 'deranged', 'derogation', 'derogatory', 'descent',
             'desecration', 'desert', 'deserted', 'desolation', 'despair', 'despairing', 'despotic', 'despotism',
             'destination', 'destitute', 'destroyed', 'destroyer', 'destroying', 'destructive', 'detainee',
             'deteriorate', 'deterioration', 'detonate', 'devastate', 'devastating', 'devastation', 'devil', 'devilish',
             'diabolical', 'diagnosis', 'dictator', 'dictatorship', 'die', 'difficult', 'difficulty', 'dike',
             'dinosaur', 'dire', 'disable', 'disabled', 'disallowed', 'disappear', 'disapprove', 'disaster',
             'disastrous', 'discipline', 'discontent', 'discontinuity', 'discourage', 'discrimination', 'disease',
             'diseased', 'disembodied', 'disfigured', 'disgust', 'disgusting', 'dishonor', 'disinformation',
             'disintegrate', 'dislocated', 'dismal', 'dismay', 'dismemberment', 'dismissal', 'disorder', 'displaced',
             'displeased', 'dispossessed', 'disreputable', 'disrespectful', 'disruption', 'dissident', 'dissolution',
             'distress', 'distressed', 'distressing', 'distrust', 'disturbance', 'divorce', 'dominant', 'dominate',
             'domination', 'dominion', 'doom', 'doomed', 'doomsday', 'doubt', 'downfall', 'dragon', 'dread', 'dreadful',
             'dreadfully', 'drown', 'dubious', 'duel', 'dungeon', 'duress', 'dwarfed', 'dying', 'earthquake', 'edict',
             'eel', 'elevation', 'elf', 'elimination', 'emaciated', 'embarrassment', 'embolism', 'emergency',
             'encroachment', 'encumbrance', 'endanger', 'endangered', 'endemic', 'endless', 'endocarditis', 'enemy',
             'enforce', 'enigmatic', 'enmity', 'enslaved', 'entangled', 'epidemic', 'eradication', 'erase', 'eruption',
             'escape', 'escaped', 'ethereal', 'euthanasia', 'evacuate', 'evade', 'evasion', 'eventuality', 'eviction',
             'evil', 'exacerbation', 'examination', 'excitation', 'excite', 'exclusion', 'excruciating', 'execution',
             'executioner', 'exigent', 'exile', 'exorcism', 'expel', 'explode', 'explosion', 'explosive', 'expose',
             'expulsion', 'exterminate', 'extermination', 'extrajudicial', 'failing', 'failure', 'fainting', 'falter',
             'fanaticism', 'fang', 'fangs', 'fatal', 'fatality', 'fear', 'fearful', 'fearfully', 'fearing', 'fearless',
             'feeling', 'felon', 'ferocious', 'fever', 'fiend', 'fierce', 'fight', 'fire', 'firearms', 'fled', 'flee',
             'flinch', 'flog', 'flood', 'flounder', 'flu', 'fluctuation', 'flying', 'foe', 'forbidding', 'force',
             'forced', 'forcibly', 'foreboding', 'foreclose', 'foreigner', 'forewarned', 'forfeiture', 'forgotten',
             'formidable', 'fortress', 'foul', 'fragile', 'frantic', 'fraught', 'freakish', 'frenetic', 'frenzied',
             'fret', 'frigate', 'fright', 'frighten', 'frightened', 'frightful', 'fugitive', 'fury', 'gallows', 'gang',
             'gash', 'gasping', 'gent', 'ghastly', 'ghetto', 'ghost', 'ghostly', 'giant', 'gladiator', 'glare', 'gnome',
             'goblin', 'god', 'gonorrhea', 'gore', 'gory', 'government', 'graduation', 'grave', 'grenade', 'grieve',
             'grievous', 'grim', 'grisly', 'grizzly', 'grope', 'grounded', 'growl', 'growling', 'guard', 'guerilla',
             'guillotine', 'gulp', 'gun', 'gunpowder', 'hag', 'hallucination', 'halter', 'halting', 'hanging',
             'hangman', 'harbinger', 'hardened', 'harm', 'harmful', 'harrowing', 'harshness', 'hate', 'hateful',
             'hatred', 'haunt', 'haunted', 'havoc', 'hawk', 'hazard', 'hazardous', 'haze', 'hearing', 'hearse',
             'heathen', 'heft', 'heighten', 'hell', 'hellish', 'helmet', 'helpless', 'helplessness', 'hemorrhage',
             'hesitation', 'hide', 'hideous', 'hiding', 'highest', 'hiss', 'holiness', 'holocaust', 'homeless',
             'homework', 'homicidal', 'homicide', 'honest', 'hood', 'hooded', 'hopeless', 'hopelessness', 'horrible',
             'horrid', 'horrific', 'horrified', 'horrifying', 'horror', 'horrors', 'hospital', 'hostage', 'hostile',
             'hostilities', 'howl', 'hunter', 'hunting', 'hurricane', 'hurt', 'hurtful', 'hurting', 'hydra',
             'hydrocephalus', 'hypertrophy', 'hysteria', 'hysterical', 'idolatry', 'ill', 'illegal', 'illegality',
             'illegitimate', 'illicit', 'illness', 'immerse', 'immigrant', 'imminent', 'immoral', 'impeach',
             'impending', 'impermeable', 'impotence', 'imprisoned', 'imprisonment', 'incarceration', 'incase',
             'incendiary', 'incest', 'incite', 'incrimination', 'incubus', 'incurable', 'incursion', 'indefensible',
             'indict', 'indictment', 'indifference', 'indoctrination', 'indomitable', 'ineptitude', 'inequality',
             'infamous', 'infant', 'infanticide', 'infarct', 'infection', 'infectious', 'inferno', 'infestation',
             'infidel', 'infidelity', 'infirmity', 'inflation', 'inflict', 'infliction', 'inhuman', 'injection',
             'injure', 'injured', 'injurious', 'injury', 'inmate', 'insane', 'insanity', 'insecure', 'insecurity',
             'insidious', 'insolvency', 'insolvent', 'instability', 'instinctive', 'insulting', 'insurmountable',
             'intelligence', 'intense', 'intercede', 'interrogate', 'interrogation', 'interviewer', 'intimately',
             'intimidate', 'intimidation', 'intolerance', 'intolerant', 'intrigue', 'intruder', 'intrusion',
             'intrusive', 'invade', 'invader', 'iris', 'irrational', 'irreconcilable', 'irreparable', 'isolated',
             'jail', 'jarring', 'jaundice', 'jaws', 'jealousy', 'jeopardize', 'jeopardy', 'journey', 'jungle',
             'kerosene', 'khan', 'kidnap', 'kill', 'killing', 'knell', 'lace', 'lament', 'landslide', 'languishing',
             'lash', 'lava', 'lawlessness', 'lawsuit', 'lawyer', 'laxative', 'leeches', 'legalized', 'leprosy',
             'lethal', 'leukemia', 'libel', 'lifeless', 'lightning', 'lines', 'lion', 'litigate', 'lockup', 'locust',
             'loneliness', 'lonely', 'loom', 'lose', 'loss', 'loyal', 'lunacy', 'lunatic', 'lynch', 'mace', 'mad',
             'madden', 'madman', 'madness', 'mafia', 'mage', 'malaria', 'malevolent', 'malice', 'malicious',
             'malignancy', 'malignant', 'mandamus', 'mange', 'mangle', 'maniac', 'manifestation', 'manipulation',
             'manslaughter', 'marry', 'martyr', 'martyrdom', 'masochism', 'massacre', 'measles', 'medical', 'melee',
             'menace', 'menacing', 'mercenary', 'merciless', 'mighty', 'military', 'militia', 'miscarriage',
             'misconception', 'misery', 'misfortune', 'mishap', 'mislead', 'missile', 'missing', 'mistaken', 'mistrust',
             'moan', 'mob', 'molestation', 'monster', 'monstrosity', 'morbidity', 'morgue', 'mortality', 'mortgage',
             'mortgagor', 'mortification', 'mortuary', 'mournful', 'mug', 'mum', 'murder', 'murderer', 'murderous',
             'musket', 'mutilation', 'mutiny', 'muzzle', 'mysterious', 'nasty', 'nefarious', 'nervous', 'nervousness',
             'nether', 'neuralgia', 'neurosis', 'neurotic', 'newcomer', 'nightmare', 'noncompliance', 'notoriety',
             'noxious', 'nurture', 'obey', 'obi', 'obliging', 'obligor', 'obliterate', 'obliterated', 'obliteration',
             'oblivion', 'obstacle', 'obstruct', 'occult', 'odious', 'offender', 'offense', 'ogre', 'omen', 'ominous',
             'omnipotence', 'opera', 'operation', 'opium', 'opponent', 'opposed', 'oppress', 'oppression', 'oppressive',
             'oppressor', 'orc', 'ordnance', 'orphan', 'outburst', 'outcast', 'outcry', 'outpost', 'outsider',
             'overpowering', 'overt', 'overthrow', 'owing', 'pain', 'pained', 'painful', 'palsy', 'pandemic', 'panic',
             'parachute', 'parade', 'paralysis', 'paralyzed', 'paranoia', 'parasite', 'pare', 'penal', 'penalty',
             'penance', 'penetration', 'perdition', 'peril', 'perilous', 'perish', 'perishing', 'perjury', 'pernicious',
             'perpetrator', 'persecute', 'persecution', 'perturbation', 'perverse', 'pessimism', 'pessimist', 'pest',
             'pestilence', 'phalanx', 'phantom', 'picket', 'pillage', 'pinion', 'pitfall', 'plague', 'plea', 'plight',
             'plummet', 'plunder', 'plunge', 'pneumonia', 'poaching', 'poison', 'poisoned', 'poisonous', 'police',
             'policeman', 'polio', 'posse', 'possessed', 'possession', 'poverty', 'powerful', 'powerfully', 'powerless',
             'pray', 'precarious', 'precipice', 'predicament', 'prejudiced', 'premeditated', 'prevent', 'prey', 'prick',
             'prison', 'prisoner', 'probation', 'problem', 'procedure', 'prognosis', 'prohibited', 'projectile',
             'projectiles', 'prosecute', 'protestant', 'prowl', 'psychosis', 'puma', 'punch', 'punish', 'punished',
             'punishing', 'punishment', 'punitive', 'purgatory', 'purge', 'quail', 'quake', 'quandary', 'quarantine',
             'quash', 'quiver', 'quivering', 'rabble', 'rabid', 'radiation', 'radioactive', 'radon', 'raging', 'raid',
             'rampage', 'ransom', 'rape', 'raptors', 'rascal', 'rat', 'rating', 'rattlesnake', 'ravenous', 'ravine',
             'raving', 'razor', 'react', 'rebel', 'rebellion', 'recesses', 'recession', 'reckless', 'recklessness',
             'refutation', 'regiment', 'regulatory', 'reject', 'rejection', 'rejects', 'rekindle', 'relapse',
             'reluctant', 'remains', 'remove', 'repellant', 'repellent', 'repent', 'repression', 'reprisal',
             'repulsion', 'resection', 'resign', 'resistant', 'resisting', 'restrain', 'restrained', 'restriction',
             'retaliation', 'retard', 'reticent', 'retirement', 'retrenchment', 'retribution', 'revenge', 'revoke',
             'revolting', 'revolution', 'revolver', 'revulsion', 'rheumatism', 'rifle', 'rigor', 'riot', 'riotous',
             'risk', 'risky', 'rob', 'robber', 'robbery', 'rod', 'romance', 'rot', 'rubble', 'ruin', 'ruined',
             'ruinous', 'rule', 'rupture', 'ruthless', 'saber', 'sabotage', 'sacrifices', 'sag', 'samurai', 'sarcoma',
             'savage', 'savagery', 'scaffold', 'scalpel', 'scandal', 'scapegoat', 'scar', 'scarce', 'scarcity', 'scare',
             'scarecrow', 'schizophrenia', 'scold', 'scorpion', 'scoundrel', 'scourge', 'scrapie', 'scream',
             'screaming', 'screech', 'seclusion', 'sectarian', 'seize', 'seizure', 'senile', 'senseless', 'sentence',
             'sepsis', 'seriousness', 'serpent', 'servile', 'settlor', 'shackle', 'shady', 'shaking', 'shaky', 'shame',
             'shanghai', 'shank', 'shatter', 'shell', 'shipwreck', 'shiver', 'shock', 'shoot', 'shooter', 'shooting',
             'shortage', 'shot', 'shrapnel', 'shriek', 'shrill', 'shrink', 'shudder', 'sickening', 'sickness', 'sin',
             'sinful', 'sinister', 'sinner', 'siren', 'skid', 'slam', 'slaughter', 'slaughterhouse', 'slaughtering',
             'slave', 'slavery', 'slayer', 'sly', 'smash', 'smite', 'smuggle', 'smuggler', 'smut', 'snake', 'snare',
             'sneak', 'sneaking', 'socialism', 'socialist', 'sorcery', 'sordid', 'sorrow', 'sortie', 'soulless',
             'soulmate', 'spank', 'spasm', 'spear', 'specter', 'speculation', 'spider', 'spike', 'spinster', 'spook',
             'sprite', 'spur', 'squall', 'squeamish', 'stab', 'stalk', 'standoff', 'startle', 'starvation', 'steal',
             'stealing', 'stealthy', 'stifled', 'stigma', 'stillness', 'sting', 'stingy', 'stint', 'stormy', 'straits',
             'stranger', 'strangle', 'stretcher', 'stripped', 'stroke', 'struggle', 'stunned', 'subjugation',
             'subordinate', 'subversion', 'subvert', 'sufferer', 'suffering', 'suffocating', 'suffocation', 'suicidal',
             'suicide', 'sultan', 'sunk', 'superstition', 'superstitious', 'suppress', 'suppression', 'supremacy',
             'surgery', 'surprise', 'surrender', 'surveillance', 'suspect', 'suspense', 'suspension', 'suspicion',
             'swamp', 'swampy', 'swastika', 'sweat', 'swelling', 'swerve', 'swim', 'sympathetic', 'syncope',
             'synonymous', 'syringe', 'taboo', 'tactics', 'talons', 'taunt', 'tearful', 'teasing', 'tempest',
             'terminal', 'terrible', 'terror', 'terrorism', 'terrorist', 'terrorize', 'theft', 'theocratic', 'thief',
             'thirteenth', 'thorny', 'thrash', 'threat', 'threaten', 'threatening', 'thresh', 'thrill', 'throb', 'thug',
             'thumping', 'thundering', 'timid', 'timidity', 'toothache', 'torment', 'tornado', 'torrent', 'torture',
             'toughness', 'towering', 'toxin', 'tract', 'tragedy', 'traitor', 'tramp', 'traumatic', 'travesty',
             'treacherous', 'treachery', 'treason', 'treat', 'trembling', 'tremor', 'trepidation', 'tribulation',
             'tribunal', 'trickery', 'troll', 'troublesome', 'tumor', 'tumour', 'tumult', 'tumultuous', 'turbulence',
             'turbulent', 'turmoil', 'typhoon', 'tyrannical', 'tyranny', 'tyrant', 'ugliness', 'ulcer', 'ultimatum',
             'unbridled', 'uncanny', 'uncertain', 'undecided', 'undesirable', 'uneasy', 'unemployed', 'unequal',
             'unexpected', 'unfriendly', 'unhealthy', 'unholy', 'unjustifiable', 'unkind', 'unknown', 'unlawful',
             'unlucky', 'unnatural', 'unrest', 'unruly', 'unsafe', 'unsettled', 'unspeakable', 'unstable', 'unsteady',
             'unsurpassed', 'unthinkable', 'upheaval', 'uphill', 'uprising', 'urgency', 'urgent', 'usurped', 'validity',
             'vampire', 'vanished', 'varicella', 'veer', 'vehement', 'vendetta', 'vengeful', 'venom', 'venomous',
             'verdict', 'verge', 'vermin', 'vertigo', 'victim', 'victimized', 'vigilant', 'villain', 'villainous',
             'violation', 'violence', 'violent', 'violently', 'viper', 'virulence', 'volatility', 'volcano',
             'volunteer', 'vulnerability', 'vulture', 'wail', 'wan', 'war', 'warden', 'ware', 'warfare', 'warlike',
             'warlock', 'warn', 'warned', 'warning', 'warrior', 'wary', 'wasting', 'watch', 'waver', 'weakly', 'weight',
             'weighty', 'weirdo', 'whimper', 'whirlpool', 'whirlwind', 'wicked', 'wilderness', 'wildfire', 'wimp',
             'wimpy', 'wince', 'witch', 'witchcraft', 'withstand', 'woe', 'worry', 'worrying', 'worse', 'worship',
             'wound', 'wrangling', 'wrath', 'wreck', 'wrecked', 'wrongly', 'xenophobia', 'yell', 'yelp', 'youth'],
    'joy': ['absolution', 'abundance', 'abundant', 'accolade', 'accompaniment', 'accomplish', 'accomplished', 'achieve',
            'achievement', 'acrobat', 'admirable', 'admiration', 'adorable', 'adoration', 'adore', 'advance', 'advent',
            'advocacy', 'aesthetics', 'affection', 'affluence', 'alive', 'allure', 'aloha', 'amazingly', 'ambition',
            'amen', 'amicable', 'amnesty', 'amour', 'amuse', 'amused', 'amusement', 'amusing', 'angel', 'angelic',
            'animated', 'applause', 'appreciation', 'approve', 'ardent', 'art', 'aspiration', 'aspire', 'aspiring',
            'astonishment', 'atone', 'auspicious', 'authentic', 'award', 'baby', 'balm', 'banquet', 'baptismal',
            'basketball', 'beach', 'beam', 'beaming', 'beautification', 'beautiful', 'beautify', 'beauty', 'beer',
            'befriend', 'benevolence', 'benign', 'betrothed', 'birth', 'birthday', 'bless', 'blessed', 'blessing',
            'blessings', 'bliss', 'blissful', 'bloom', 'blossom', 'boisterous', 'bonanza', 'bonus', 'bountiful',
            'bounty', 'bouquet', 'bridal', 'bride', 'bridegroom', 'bridesmaid', 'brighten', 'brilliant', 'brotherly',
            'buddy', 'buss', 'calf', 'candid', 'captivate', 'carol', 'cash', 'cathedral', 'celebrated', 'celebrating',
            'celebration', 'celebrity', 'celestial', 'ceremony', 'champion', 'chant', 'charitable', 'charity',
            'charmed', 'cheer', 'cheerful', 'cheerfulness', 'cheering', 'cheery', 'cherish', 'child', 'childhood',
            'chirp', 'chocolate', 'choir', 'choral', 'chuckle', 'church', 'civilized', 'clap', 'classics', 'clean',
            'climax', 'closeness', 'closure', 'clown', 'comfort', 'commemorate', 'commemoration', 'commendable',
            'communion', 'companion', 'compensate', 'complement', 'completing', 'completion', 'compliment',
            'conciliation', 'confidence', 'confident', 'congratulatory', 'connoisseur', 'consecration', 'content',
            'coronation', 'courtship', 'cove', 'cradle', 'cream', 'create', 'crescendo', 'crowning', 'cuddle', 'dance',
            'darling', 'daughter', 'dawn', 'deal', 'delicious', 'delight', 'delighted', 'delightful', 'deliverance',
            'demonstrative', 'destination', 'devout', 'diamond', 'diary', 'ditty', 'doll', 'dolphin', 'dove', 'eager',
            'eagerness', 'ecstasy', 'ecstatic', 'edification', 'ejaculation', 'elated', 'electric', 'elegance',
            'elegant', 'elevation', 'elite', 'emancipation', 'embrace', 'enchant', 'enchanted', 'enchanting',
            'encourage', 'endless', 'engaged', 'engaging', 'enjoy', 'enjoying', 'enlighten', 'enlightenment', 'enliven',
            'entertain', 'entertained', 'entertaining', 'entertainment', 'enthusiasm', 'enthusiast', 'equality',
            'erotic', 'established', 'esteem', 'evergreen', 'exalt', 'exaltation', 'exalted', 'exceed', 'excel',
            'excellence', 'excellent', 'excitation', 'excite', 'excited', 'excitement', 'exciting', 'exhilaration',
            'expedient', 'exquisite', 'exuberance', 'fain', 'faith', 'familiarity', 'fancy', 'fanfare', 'favorable',
            'favorite', 'feat', 'feeling', 'felicity', 'fervor', 'festival', 'festive', 'fete', 'fidelity', 'fiesta',
            'finally', 'firstborn', 'fitting', 'flattering', 'flirt', 'fondness', 'food', 'football', 'forefathers',
            'fortitude', 'fortune', 'found', 'fraternal', 'freedom', 'freely', 'friend', 'friendliness', 'friendly',
            'friendship', 'frisky', 'frolic', 'fulfill', 'fulfillment', 'fun', 'gain', 'garden', 'gem', 'generosity',
            'generous', 'genial', 'gift', 'giggle', 'glad', 'gladness', 'glee', 'glide', 'glimmer', 'glitter',
            'glorification', 'glorify', 'glory', 'glow', 'god', 'godly', 'godsend', 'good', 'goodness', 'gorgeous',
            'graduation', 'grandchildren', 'grant', 'gratify', 'gratitude', 'greatness', 'green', 'grin', 'grow',
            'gush', 'happily', 'happiness', 'happy', 'hardy', 'harmoniously', 'harmony', 'harvest', 'heal', 'healing',
            'healthful', 'heartfelt', 'heartily', 'heavenly', 'heavens', 'hedonism', 'helpful', 'hero', 'heroic',
            'heroism', 'heyday', 'highest', 'hilarious', 'hilarity', 'hire', 'hobby', 'holiday', 'holiness', 'honest',
            'honeymoon', 'hope', 'hopeful', 'hug', 'humanitarian', 'humanity', 'humorous', 'hurrah', 'hymn',
            'illuminate', 'illumination', 'immaculate', 'immerse', 'improve', 'improvement', 'inauguration', 'income',
            'independence', 'infant', 'infinity', 'inheritance', 'inseparable', 'inspiration', 'inspire', 'inspired',
            'intelligence', 'intense', 'intimate', 'intimately', 'invite', 'inviting', 'jackpot', 'jest', 'joker',
            'journey', 'jovial', 'joy', 'joyful', 'joyous', 'jubilant', 'jubilee', 'jump', 'kind', 'kindred', 'kiss',
            'kitten', 'kudos', 'labor', 'lamb', 'laugh', 'laughing', 'laughter', 'laurels', 'legalized', 'leisure',
            'liberate', 'liberation', 'liberty', 'liking', 'liquor', 'lovable', 'love', 'lovely', 'lovemaking', 'lover',
            'loving', 'loyal', 'luck', 'lucky', 'luscious', 'luster', 'luxurious', 'luxury', 'lyre', 'lyrical',
            'magical', 'magnificence', 'magnificent', 'majestic', 'majority', 'marriage', 'marrow', 'marry',
            'marvelous', 'marvelously', 'massage', 'masterpiece', 'mastery', 'matrimony', 'medal', 'meditate',
            'memorable', 'meritorious', 'merriment', 'merry', 'midwife', 'mighty', 'ministry', 'miracle', 'miraculous',
            'mirth', 'money', 'morals', 'mother', 'motherhood', 'music', 'musical', 'nap', 'notable', 'nursery',
            'nurture', 'oasis', 'obliging', 'obtainable', 'opera', 'opportune', 'optimism', 'orchestra', 'ordination',
            'organ', 'organization', 'orgasm', 'outburst', 'outstanding', 'overjoyed', 'parade', 'paragon', 'passion',
            'passionate', 'pastor', 'pastry', 'pay', 'peace', 'peaceful', 'perfect', 'perfection', 'picnic',
            'picturesque', 'playful', 'playground', 'playhouse', 'pleasant', 'pleased', 'pleasurable', 'pledge',
            'possess', 'powerful', 'practiced', 'praise', 'praised', 'praiseworthy', 'pray', 'precious', 'present',
            'preservative', 'prestige', 'presto', 'pretty', 'prevail', 'pride', 'priesthood', 'princely', 'privileged',
            'procession', 'proficiency', 'progress', 'progression', 'promise', 'prosper', 'prosperous', 'proud',
            'providing', 'purify', 'purr', 'quaint', 'radiance', 'radiant', 'rapt', 'rapture', 'rave', 'raving',
            'readiness', 'receiving', 'reconciliation', 'recreation', 'recreational', 'rejoice', 'rejoicing',
            'rekindle', 'remarkable', 'remedy', 'renovation', 'repay', 'reproductive', 'rescue', 'resources', 'respect',
            'respite', 'resplendent', 'restorative', 'retirement', 'revel', 'revels', 'revere', 'reverence', 'reverend',
            'reverie', 'revival', 'reward', 'rhythmical', 'ribbon', 'rising', 'roadster', 'rollicking', 'romance',
            'romantic', 'romanticism', 'romp', 'safe', 'saint', 'saintly', 'salary', 'salutary', 'salute', 'salvation',
            'sanctification', 'sanctify', 'sanctuary', 'satisfied', 'save', 'savor', 'scholarship', 'score',
            'sensational', 'sensual', 'sensuality', 'sensuous', 'serenity', 'sex', 'share', 'shining', 'shopping',
            'silly', 'simplify', 'sing', 'smile', 'smiling', 'sonnet', 'sonorous', 'soothing', 'soundness', 'spa',
            'spaniel', 'sparkle', 'special', 'spirits', 'splendid', 'splendor', 'spouse', 'star', 'starry', 'sterling',
            'strengthening', 'sublimation', 'succeed', 'succeeding', 'success', 'successful', 'sun', 'sunny',
            'sunshine', 'superman', 'superstar', 'supporter', 'supremacy', 'surprise', 'sweet', 'sweetheart', 'sweets',
            'swim', 'symmetry', 'sympathetic', 'symphony', 'synchronize', 'tantalizing', 'teach', 'tender',
            'tenderness', 'thankful', 'thanksgiving', 'therapeutic', 'thrill', 'thrilling', 'thriving', 'tickle',
            'tinsel', 'toast', 'tranquil', 'tranquility', 'transcendence', 'treasure', 'treat', 'tree', 'triumph',
            'triumphant', 'trophy', 'truce', 'TRUE', 'twinkle', 'unbeaten', 'unconstrained', 'undying', 'unexpected',
            'unification', 'unsurpassed', 'untie', 'uplift', 'utopian', 'vacation', 'venerable', 'veracity', 'vernal',
            'victor', 'victorious', 'victory', 'vindication', 'virtuous', 'visionary', 'visitor', 'vitality',
            'vivacious', 'vivid', 'volunteer', 'voluptuous', 'vote', 'vow', 'wages', 'wealth', 'weight', 'welcomed',
            'whim', 'whimsical', 'white', 'whiteness', 'winner', 'winning', 'winnings', 'witty', 'wonderful',
            'wonderfully', 'worship', 'yearning', 'young', 'youth', 'zeal', 'zealous', 'zest'],
    'sadness': ['abandon', 'abandoned', 'abandonment', 'abduction', 'abortion', 'abortive', 'abscess', 'absence',
                'absent', 'absentee', 'abuse', 'abysmal', 'abyss', 'accident', 'accursed', 'ache', 'aching', 'adder',
                'adrift', 'adultery', 'adverse', 'adversity', 'afflict', 'affliction', 'affront', 'aftermath',
                'aggravating', 'agony', 'ail', 'ailing', 'alcoholism', 'alienated', 'alienation', 'anathema',
                'anchorage', 'anguish', 'animosity', 'annihilated', 'annihilation', 'annulment', 'anthrax',
                'antisocial', 'anxiety', 'apathetic', 'apathy', 'apologize', 'appendicitis', 'arid', 'arraignment',
                'arsenic', 'art', 'ashamed', 'ashes', 'assailant', 'assassin', 'assassination', 'atherosclerosis',
                'atrocity', 'atrophy', 'attacking', 'attenuation', 'austere', 'autopsy', 'avalanche', 'awful',
                'backwater', 'bacteria', 'bad', 'badly', 'bang', 'banish', 'banished', 'banishment', 'bankrupt',
                'bankruptcy', 'banshee', 'barren', 'bastard', 'battered', 'battled', 'beating', 'beg', 'beggar',
                'belittle', 'bereaved', 'bereavement', 'betray', 'betrayal', 'bier', 'bigoted', 'bitch', 'bitterly',
                'bitterness', 'black', 'blackness', 'bleak', 'bleeding', 'blemish', 'blight', 'blighted', 'blindly',
                'blindness', 'blockade', 'bloodshed', 'bloody', 'blue', 'blues', 'blunder', 'bomb', 'bomber', 'bondage',
                'boredom', 'bothering', 'bottom', 'breakup', 'broke', 'broken', 'brute', 'bugaboo', 'bum', 'burdensome',
                'burial', 'buried', 'burke', 'bury', 'cadaver', 'cage', 'calamity', 'cancel', 'cancer', 'captive',
                'captivity', 'carcass', 'carcinoma', 'cardiomyopathy', 'carnage', 'case', 'casket', 'casualty',
                'cataract', 'catastrophe', 'cemetery', 'chagrin', 'chaos', 'chargeable', 'choke', 'cholera', 'chronic',
                'closure', 'clouded', 'cloudy', 'cocaine', 'coercion', 'coffin', 'coldness', 'collapse', 'collusion',
                'coma', 'comatose', 'commemorate', 'committal', 'communism', 'complain', 'conceal', 'concerned',
                'concussion', 'condemnation', 'condescension', 'condolence', 'confession', 'confine', 'confined',
                'confinement', 'confiscate', 'conflict', 'consecration', 'console', 'constraint', 'contaminated',
                'convict', 'corpse', 'corrupting', 'corse', 'couch', 'coward', 'crash', 'crazy', 'cremation', 'cringe',
                'cripple', 'crippled', 'criticism', 'criticize', 'cross', 'crucifixion', 'cruel', 'cruelty',
                'crumbling', 'crushed', 'cry', 'crying', 'crypt', 'cumbersome', 'cupping', 'curse', 'cursed', 'cutting',
                'cyst', 'cytomegalovirus', 'daemon', 'damage', 'damages', 'damnation', 'danger', 'dark', 'darken',
                'darkened', 'darkness', 'dashed', 'deadly', 'death', 'debacle', 'debt', 'decay', 'decayed', 'deceased',
                'deceit', 'deceitful', 'deceive', 'decomposed', 'decomposition', 'default', 'defeated', 'defendant',
                'defenseless', 'deflate', 'deformed', 'deformity', 'defunct', 'defy', 'degeneracy', 'degrading',
                'delay', 'delirious', 'delirium', 'deluge', 'delusion', 'dementia', 'demise', 'demolish', 'demon',
                'demonic', 'demonstrative', 'demoralized', 'denied', 'depart', 'departed', 'departure', 'dependence',
                'deplorable', 'deplore', 'deport', 'deportation', 'depraved', 'depreciated', 'depress', 'depressed',
                'depressing', 'depression', 'depressive', 'deprivation', 'derogation', 'derogatory', 'descent',
                'desecration', 'desert', 'deserted', 'desolation', 'despair', 'despairing', 'despotism', 'destination',
                'destitute', 'destroyed', 'destroying', 'detainee', 'detention', 'deteriorate', 'deteriorated',
                'deterioration', 'devastate', 'devastating', 'devastation', 'deviation', 'devil', 'dictatorship', 'die',
                'difficulties', 'difficulty', 'dilapidated', 'diminish', 'dire', 'disability', 'disable', 'disabled',
                'disagreeing', 'disagreement', 'disallowed', 'disappoint', 'disappointed', 'disappointing',
                'disappointment', 'disapproval', 'disapprove', 'disapproved', 'disapproving', 'disaster', 'disastrous',
                'discolored', 'discomfort', 'disconnect', 'disconnected', 'discontent', 'discontinuity', 'discourage',
                'discriminate', 'discrimination', 'disease', 'diseased', 'disembodied', 'disfigured', 'disgrace',
                'disgraced', 'disgruntled', 'disgust', 'disheartened', 'disheartening', 'dishonest', 'dishonor',
                'disillusionment', 'disliked', 'dislocated', 'dismal', 'dismay', 'dismemberment', 'dismissal',
                'disparage', 'disparaging', 'disparity', 'dispassionate', 'dispel', 'displaced', 'displeased',
                'dispossessed', 'disqualified', 'disqualify', 'disrespectful', 'disservice', 'dissolution',
                'distraught', 'distress', 'disturbance', 'disturbed', 'divorce', 'doldrums', 'dole', 'dolor',
                'domination', 'doomed', 'doomsday', 'doubt', 'downfall', 'drab', 'dreadful', 'dreadfully', 'dreary',
                'drown', 'drugged', 'dull', 'dumps', 'duress', 'dwarfed', 'dying', 'dysentery', 'earthquake',
                'elimination', 'emaciated', 'embarrass', 'embarrassment', 'embolism', 'emergency', 'emptiness',
                'encumbrance', 'endemic', 'endless', 'endocarditis', 'enmity', 'enslaved', 'entangled', 'epidemic',
                'epitaph', 'error', 'eschew', 'esteem', 'euthanasia', 'evanescence', 'evasion', 'evict', 'eviction',
                'evil', 'excluded', 'excluding', 'exclusion', 'execution', 'executioner', 'exhausted', 'exhaustion',
                'exile', 'exorcism', 'expel', 'expire', 'explode', 'expulsion', 'exterminate', 'extinct', 'failing',
                'failure', 'fainting', 'faithless', 'fall', 'falling', 'famine', 'fasting', 'fat', 'fatal', 'fatality',
                'fatigued', 'fatty', 'fault', 'fearful', 'fearfully', 'feeble', 'feeling', 'fell', 'feudalism',
                'flaccid', 'flaw', 'fleece', 'flinch', 'flog', 'flop', 'flounder', 'forbid', 'foreclose', 'forfeit',
                'forfeiture', 'forgotten', 'forlorn', 'forsake', 'forsaken', 'fortress', 'fragile', 'frailty',
                'fraught', 'frayed', 'frighten', 'frightful', 'frown', 'frowning', 'fruitless', 'frustrate', 'fugitive',
                'funeral', 'funk', 'furrow', 'fury', 'fuss', 'futile', 'gallows', 'geriatric', 'ghetto', 'gloom',
                'gloomy', 'glum', 'gonorrhea', 'gore', 'gory', 'grave', 'gray', 'grief', 'grievance', 'grieve',
                'grievous', 'grim', 'groan', 'grounded', 'grumpy', 'guillotine', 'guilt', 'guilty', 'gullible',
                'haggard', 'halter', 'halting', 'hamstring', 'handicap', 'hanging', 'hardship', 'harmful', 'harry',
                'hate', 'hateful', 'hatred', 'haunted', 'hearse', 'heartache', 'heartfelt', 'heartless', 'hell',
                'hellish', 'helpless', 'helplessness', 'hemorrhage', 'hermit', 'hideous', 'hindering', 'hoary', 'hoax',
                'hobo', 'hollow', 'holocaust', 'homeless', 'homesick', 'homicide', 'honest', 'hopeless', 'hopelessness',
                'horrid', 'horrific', 'horrifying', 'horror', 'horrors', 'hospice', 'hospital', 'howl', 'humble',
                'humbled', 'humbug', 'humiliate', 'humiliation', 'hunter', 'hurt', 'hurtful', 'hurting', 'hut',
                'hydrocephalus', 'hymn', 'idiocy', 'ill', 'illegal', 'illegitimate', 'illness', 'immoral', 'impossible',
                'impotence', 'imprisoned', 'imprisonment', 'imprudent', 'inability', 'inadequate', 'inappropriate',
                'incarceration', 'incase', 'incest', 'income', 'incompatible', 'incompetent', 'inconsequential',
                'inconsiderate', 'inconvenient', 'incrimination', 'incurable', 'indifference', 'indigent',
                'inefficiency', 'inefficient', 'ineptitude', 'inequality', 'inexcusable', 'infamy', 'infanticide',
                'infectious', 'inferior', 'infertility', 'infidelity', 'inflict', 'infliction', 'inhibit',
                'inhospitable', 'inhuman', 'inhumanity', 'inimical', 'injure', 'injured', 'injurious', 'injury',
                'insanity', 'insecure', 'insignificant', 'insolvency', 'insolvent', 'insult', 'insulting',
                'insurmountable', 'inter', 'intercede', 'interested', 'interment', 'interrupted', 'intervention',
                'intolerant', 'invade', 'invader', 'invalid', 'irreconcilable', 'irreparable', 'irritation', 'isolate',
                'isolated', 'isolation', 'jail', 'jarring', 'jealousy', 'jurisprudence', 'kennel', 'kidnap', 'kill',
                'killing', 'knell', 'labored', 'lace', 'lagging', 'lament', 'lamenting', 'landslide', 'languishing',
                'late', 'lawsuit', 'lax', 'leave', 'leprosy', 'lesbian', 'lethal', 'lethargy', 'leukemia', 'lie',
                'lifeless', 'limited', 'liquor', 'listless', 'litigate', 'lockup', 'lone', 'loneliness', 'lonely',
                'lonesome', 'longing', 'lose', 'losing', 'loss', 'lost', 'lovely', 'lower', 'lowest', 'lowly', 'lunacy',
                'lush', 'lynch', 'mad', 'malaise', 'malaria', 'malevolent', 'malicious', 'malignancy', 'mangle',
                'manslaughter', 'margin', 'martyr', 'martyrdom', 'massacre', 'mausoleum', 'meaningless', 'measles',
                'meek', 'melancholic', 'melancholy', 'melodrama', 'meltdown', 'memorials', 'militia', 'miscarriage',
                'miserable', 'miserably', 'misery', 'misfortune', 'mishap', 'misrepresentation', 'missing', 'mistake',
                'misunderstanding', 'moan', 'mocking', 'molestation', 'monsoon', 'moody', 'morbid', 'morbidity',
                'morgue', 'moribund', 'mortality', 'mortification', 'mortuary', 'mother', 'mourn', 'mournful',
                'mourning', 'mug', 'murder', 'murderer', 'murderous', 'murky', 'music', 'musical', 'mutilation',
                'myopia', 'napkin', 'nasty', 'nauseous', 'necessity', 'nefarious', 'negative', 'neglected', 'negro',
                'nepotism', 'nether', 'neuralgia', 'neurosis', 'noncompliance', 'nonsensical', 'noose', 'nothingness',
                'numbness', 'nutritious', 'obesity', 'obit', 'obituary', 'obliterate', 'obliteration', 'obnoxious',
                'obstacle', 'oddity', 'offended', 'offender', 'offense', 'older', 'onerous', 'opera', 'opium',
                'oppress', 'oppression', 'oppressive', 'oppressor', 'orchestra', 'orphan', 'oust', 'outburst',
                'outcast', 'ovation', 'overdue', 'overload', 'overpriced', 'overwhelmed', 'owing', 'pain', 'pained',
                'painful', 'painfully', 'palsy', 'pandemic', 'paralysis', 'paralyzed', 'pare', 'parting', 'pathetic',
                'paucity', 'pauper', 'penal', 'penalty', 'penance', 'pensive', 'perdition', 'peril', 'perilous',
                'perish', 'perished', 'perishing', 'pernicious', 'perpetrator', 'perplexity', 'persecution',
                'perversion', 'pessimism', 'pessimist', 'pine', 'pious', 'pitfall', 'pity', 'plague', 'plaintive',
                'plea', 'plight', 'plunder', 'poaching', 'pointless', 'poison', 'poisoned', 'poisonous', 'polio',
                'posthumous', 'poverty', 'powerless', 'precarious', 'priesthood', 'prison', 'prisoner', 'probation',
                'problem', 'procession', 'progression', 'prosecute', 'prostitution', 'psychosis', 'punch', 'punished',
                'punishing', 'punitive', 'quiet', 'rabid', 'rack', 'rainy', 'rape', 'rating', 'ravenous', 'recession',
                'recidivism', 'refugee', 'refused', 'regret', 'regrettable', 'regretted', 'regretting', 'reject',
                'rejection', 'rejects', 'relapse', 'relics', 'remiss', 'remorse', 'remove', 'repress', 'reprisal',
                'reproach', 'requiem', 'resentment', 'resign', 'resignation', 'resigned', 'resisting', 'restrict',
                'restriction', 'retard', 'retirement', 'retribution', 'revoke', 'revolution', 'revolver', 'rheumatism',
                'ridicule', 'rob', 'robbery', 'romance', 'rot', 'rubble', 'rue', 'ruin', 'ruined', 'ruinous', 'rumor',
                'runaway', 'rupture', 'sabotage', 'sacrifices', 'sadly', 'sadness', 'sanctify', 'sap', 'sarcasm',
                'sarcoma', 'savor', 'scar', 'scarce', 'scarcely', 'scarcity', 'schizophrenia', 'scold', 'scourge',
                'scrapie', 'secluded', 'sedition', 'segregate', 'senile', 'senseless', 'sentence', 'sepsis',
                'sequestration', 'seriousness', 'servile', 'setback', 'severance', 'shack', 'shackle', 'shame',
                'shameful', 'shatter', 'shattered', 'shell', 'shipwreck', 'shiver', 'shortage', 'shot', 'shriek',
                'shrink', 'shroud', 'shun', 'sick', 'sickening', 'sickly', 'sickness', 'sin', 'sinful', 'sing',
                'sinner', 'sisterhood', 'skid', 'slaughter', 'slaughterhouse', 'slaughtering', 'slave', 'slavery',
                'slayer', 'sluggish', 'slump', 'slur', 'smite', 'snort', 'sob', 'socialist', 'soldier', 'somber',
                'sonnet', 'sordid', 'sore', 'sorely', 'soreness', 'sorrow', 'sorrowful', 'soulless', 'spank', 'specter',
                'speculation', 'spinster', 'splitting', 'spoiler', 'sprain', 'squall', 'stab', 'stagnant', 'starvation',
                'steal', 'sterile', 'stifled', 'stigma', 'stillborn', 'stillness', 'stingy', 'stint', 'strangle',
                'stretcher', 'stricken', 'strip', 'stripped', 'stroke', 'struggle', 'subjected', 'subjugation',
                'subsidence', 'subvert', 'sue', 'sufferer', 'suffering', 'suffocating', 'suicidal', 'suicide', 'sullen',
                'sunk', 'suppress', 'surgery', 'surrender', 'surrendering', 'sweetheart', 'sympathetic', 'sympathize',
                'sympathy', 'syncope', 'taint', 'tarnish', 'taunt', 'tax', 'tearful', 'tease', 'tempest', 'terminal',
                'terminate', 'termination', 'terrible', 'terribly', 'terrific', 'terrorism', 'terrorist', 'terrorize',
                'theft', 'theocratic', 'thief', 'thirst', 'thrash', 'thresh', 'throb', 'timid', 'tolerate', 'tomb',
                'torment', 'torture', 'touchy', 'tough', 'tragedy', 'traitor', 'tramp', 'trash', 'traumatic',
                'travesty', 'treachery', 'treat', 'tremor', 'tribulation', 'trickery', 'tripping', 'tumour', 'turmoil',
                'tyranny', 'tyrant', 'ugliness', 'ulcer', 'ultimate', 'unable', 'unacceptable', 'unaccountable',
                'unacknowledged', 'unattainable', 'unattractive', 'unbearable', 'unbeaten', 'uncaring', 'underpaid',
                'undertaker', 'undesirable', 'undesired', 'undying', 'uneasiness', 'uneducated', 'unemployed',
                'unequal', 'unexplained', 'unfair', 'unfairness', 'unfavorable', 'unforgiving', 'unfortunate',
                'unfriendly', 'unfulfilled', 'ungodly', 'unhappiness', 'unhappy', 'unhealthy', 'unimportant',
                'uninspired', 'uninterested', 'uninteresting', 'uninvited', 'unkind', 'unlawful', 'unlucky', 'unpaid',
                'unpleasant', 'unpopular', 'unpublished', 'unrequited', 'unrest', 'unsatisfied', 'unseat',
                'unsuccessful', 'untitled', 'unwelcome', 'unwell', 'upheaval', 'upset', 'urn', 'vainly', 'vanished',
                'varicella', 'veal', 'vegetative', 'vendetta', 'victim', 'victimized', 'violation', 'violence',
                'violently', 'vote', 'vulgarity', 'vulnerability', 'waffle', 'wail', 'wallow', 'wan', 'wane', 'wanting',
                'warfare', 'warp', 'wasteful', 'wasting', 'weakly', 'wearily', 'weariness', 'weary', 'weeds', 'weep',
                'weeping', 'weight', 'whimper', 'whine', 'widow', 'widower', 'wilderness', 'wildfire', 'willful',
                'wimpy', 'wince', 'winning', 'witchcraft', 'withdraw', 'wither', 'woe', 'woeful', 'woefully', 'worn',
                'worried', 'worry', 'worrying', 'worse', 'worsening', 'worthless', 'wound', 'wrangling', 'wreck',
                'wrecked', 'wretch', 'wretched', 'wrinkled', 'wrongdoing', 'wrongful', 'wrongly'],
    'surprise': ['abandonment', 'abduction', 'abrupt', 'accident', 'accidental', 'accidentally', 'accolade', 'advance',
                 'affront', 'aghast', 'alarm', 'alarming', 'alertness', 'alerts', 'allure', 'amaze', 'amazingly',
                 'ambush', 'angel', 'anomaly', 'apparition', 'applause', 'art', 'aspiration', 'assail', 'assessment',
                 'astonishingly', 'astonishment', 'attacking', 'avalanche', 'award', 'bang', 'banger', 'betray',
                 'bewildered', 'bewilderment', 'birthday', 'bizarre', 'blast', 'blessings', 'blindfold', 'blitz',
                 'bloodshed', 'bomb', 'bonus', 'break', 'brighten', 'buck', 'burlesque', 'cable', 'cadaver',
                 'camouflage', 'camouflaged', 'candid', 'captivate', 'carnage', 'catastrophe', 'catch', 'celebration',
                 'celebrity', 'ceremony', 'chance', 'changeable', 'chant', 'cheer', 'cheerful', 'cherish', 'chicane',
                 'chimera', 'chuckle', 'clamor', 'climax', 'clown', 'coincidence', 'compensate', 'complement',
                 'compliment', 'concealed', 'confession', 'conjure', 'coup', 'crash', 'cream', 'crescendo', 'crowning',
                 'curiosity', 'cyclone', 'daemon', 'dawn', 'deal', 'death', 'deceit', 'decoy', 'defy', 'delighted',
                 'deluge', 'destination', 'detonate', 'devastation', 'differently', 'dire', 'disaster', 'dismay',
                 'dismissal', 'disruption', 'dissolution', 'distress', 'disturbance', 'divergent', 'diversion',
                 'divorce', 'dolphin', 'dreadfully', 'dynamic', 'eager', 'earthquake', 'ecstatic', 'ejaculation',
                 'electric', 'elusive', 'embarrassment', 'embrace', 'emergency', 'enchant', 'enliven', 'entertainment',
                 'enthusiasm', 'enthusiast', 'epidemic', 'erotic', 'erratic', 'erupt', 'eruption', 'evanescence',
                 'examination', 'excavation', 'excel', 'excitation', 'excite', 'excited', 'excitement', 'exciting',
                 'exclaim', 'exhilaration', 'exigent', 'expect', 'experiment', 'explode', 'explosion', 'explosive',
                 'fainting', 'fanfare', 'favorable', 'fearfully', 'feat', 'feeling', 'festival', 'fete', 'fiesta',
                 'finally', 'flinch', 'flirt', 'fluke', 'foresee', 'fortune', 'frantic', 'freakish', 'frenetic',
                 'fright', 'frighten', 'frightened', 'frisky', 'gambler', 'gambling', 'gape', 'garish', 'gasp', 'gawk',
                 'generosity', 'gift', 'glimmer', 'glorify', 'godsend', 'good', 'goodness', 'graduation', 'gratify',
                 'greatness', 'greeting', 'grin', 'guess', 'gulp', 'hap', 'hermaphrodite', 'hero', 'heroic', 'heroism',
                 'highest', 'hilarious', 'hoax', 'holiness', 'honeymoon', 'hope', 'hopeful', 'horde', 'horror', 'howl',
                 'humanitarian', 'hypertrophy', 'hypothesis', 'illegitimate', 'illuminate', 'illumination', 'illusion',
                 'immediacy', 'immerse', 'improvisation', 'improvise', 'incendiary', 'incident', 'incontinence',
                 'independence', 'inexplicable', 'infant', 'infarct', 'infrequent', 'inheritance', 'insolvency',
                 'inspired', 'insult', 'intense', 'interrupt', 'intrigue', 'intruder', 'intrusive', 'invade', 'invite',
                 'inviting', 'jackpot', 'jerk', 'jest', 'joker', 'jolt', 'jubilant', 'jubilee', 'judgment', 'kidnap',
                 'kiss', 'labor', 'larger', 'latent', 'laugh', 'laughter', 'lawsuit', 'leave', 'leery', 'leisure',
                 'liberate', 'liberation', 'liberty', 'lightning', 'lose', 'lovely', 'loyal', 'luck', 'lucky', 'lunge',
                 'magical', 'magician', 'magnificent', 'majestic', 'manslaughter', 'marry', 'marvel', 'medal',
                 'memorable', 'merriment', 'mimicry', 'miracle', 'miraculous', 'misbehavior', 'mishap', 'modify',
                 'money', 'monstrosity', 'morals', 'mouth', 'murder', 'murderous', 'musical', 'mutiny', 'mysterious',
                 'mystery', 'mystic', 'nab', 'nefarious', 'newcomer', 'nullify', 'obit', 'obliging', 'occasional',
                 'oddity', 'opera', 'optimism', 'ordeal', 'organization', 'originality', 'outburst', 'outcry',
                 'outrageous', 'overdue', 'overestimate', 'palpable', 'pang', 'parade', 'paralyzed', 'peaceful',
                 'perchance', 'perfection', 'peri', 'perjury', 'picnic', 'pitfall', 'placard', 'playful', 'playground',
                 'pleasant', 'plunder', 'polarity', 'pop', 'postponement', 'practiced', 'praiseworthy', 'prank', 'pray',
                 'precious', 'premature', 'present', 'preservative', 'presto', 'prick', 'princely', 'procession',
                 'proficiency', 'prowl', 'puma', 'punch', 'purity', 'quickness', 'quicksilver', 'quote', 'raffle',
                 'raid', 'randomly', 'rapid', 'rapt', 'rarity', 'rave', 'raving', 'reappear', 'receiving',
                 'recklessness', 'reflex', 'rejoice', 'rejoicing', 'rekindle', 'remarkable', 'rescue', 'resignation',
                 'revenge', 'reversal', 'revolt', 'revolution', 'reward', 'rhythmical', 'riddle', 'riotous', 'romance',
                 'rupture', 'sabotage', 'saint', 'saintly', 'sally', 'sanctify', 'scare', 'score', 'scorpion', 'scream',
                 'screech', 'scrimmage', 'secrecy', 'senseless', 'sensual', 'shatter', 'shell', 'shock', 'shockingly',
                 'shopping', 'shot', 'shout', 'shriek', 'shrill', 'simplify', 'singularly', 'sisterhood', 'slam',
                 'slap', 'slaughter', 'slaughtering', 'slayer', 'slip', 'slush', 'smile', 'snag', 'sneak', 'sneeze',
                 'somatic', 'sorcery', 'spa', 'sparkle', 'spectacular', 'spirits', 'splash', 'splendid', 'splendor',
                 'stab', 'stagger', 'startle', 'startling', 'steady', 'stealth', 'stealthily', 'stealthy', 'strangle',
                 'stunned', 'subito', 'subversive', 'succeed', 'sudden', 'suddenly', 'sun', 'sunny', 'supremacy',
                 'surge', 'surprise', 'surprised', 'surprising', 'surprisingly', 'suspense', 'sweet', 'swerve',
                 'synchronize', 'syncope', 'tackle', 'tantalizing', 'teach', 'tempest', 'terrorist', 'thief', 'thirst',
                 'thrill', 'thrilling', 'thwart', 'tickle', 'topple', 'transcendence', 'treachery', 'treason', 'treat',
                 'tree', 'trepidation', 'trick', 'trickery', 'trip', 'trophy', 'trump', 'tumult', 'unanticipated',
                 'unbeaten', 'unbridled', 'uncanny', 'uncertain', 'uncontrollable', 'uncover', 'underestimate',
                 'undiscovered', 'unexpected', 'unexpectedly', 'unforeseen', 'unfulfilled', 'unguarded', 'unimaginable',
                 'unintended', 'unintentional', 'unintentionally', 'unique', 'unprecedented', 'unpredictable',
                 'unstable', 'unsuspecting', 'urgency', 'urgent', 'vanish', 'vanished', 'variable', 'veer', 'veracity',
                 'victimized', 'violation', 'violent', 'visor', 'volatility', 'volcano', 'vote', 'warn', 'warned',
                 'weight', 'whim', 'wild', 'wildfire', 'winner', 'winning', 'wireless', 'wizard', 'wonderful',
                 'wonderfully', 'worm', 'wreck', 'yell', 'yelp', 'young', 'youth', 'zany', 'zeal'],
}

anger_counter = 0
joy_counter = 0


def file_read(fname):
    with open(fname, "r") as f:
        text = f.read()
        print("raw text:", text)
        return text

    content_array = []
    # file_read('D:\\Course Content\\PoU\\Day 6\\Emotions\\Surprise.txt')

import re

word_list = re.split(r"\W+", file_read(r'C:\Users\Philip\PycharmProjects\reddit_scripts\Chapter1Lines.txt')) # .strip())
print("word_list:", word_list)
for word in word_list:
    print("word:", word)
    for word in word_list:
        print("word:", word)
        for emotion in emotions:
            print("emotion:", emotion)
            emotion_list = emotions[emotion]
            print("emotion_list length", len(emotion_list))
            print("word in emotion_list:",(word in emotion_list))
            if word in emotion_list:
                pass

#file_read()