def Phillyclause89_comma_and(spam):
    n, s = len(spam) - 1, ""
    for i in range(n):
        if i == n - 1:
            s += "{} and {}.".format(spam[i], spam[i + 1])
        else:
            s += "{}, ".format(spam[i])
    return s


def TedTheTwonk_comma_and(list_of_words):
    return f"{', '.join(list_of_words[:-1])}{',' if len(list_of_words) >= 3 else ''}{' and ' if len(list_of_words) >= 2 else ''}{list_of_words[-1] if len(list_of_words) >= 1 else ''}"


def Binary101010_comma_and(spam):
    last = spam.pop()
    return f"{', '.join(spam)}, and {last}"


def o5a_comma_and(spam):
    return ', '.join(spam[:-1]) + ' and ' + spam[-1]


def guipalazzo_comma_and(spam):
    for i in range(len(spam)):
        if i < len(spam) - 2:
            print(spam[i] + ', ', end='')
        elif i < len(spam) - 1:
            print(spam[i] + ' ', end='')
        else:
            print('and ' + spam[i] + '.')


spam = ['apples', 'bananas', 'tofu', 'cats']

philly = Phillyclause89_comma_and(spam)
ted = TedTheTwonk_comma_and(spam)
bin = Binary101010_comma_and(spam)
o5a = o5a_comma_and(spam)
gui = guipalazzo_comma_and(spam)

spam1000 = ["volume", "separate", "completely", "beat", "table", "express", "vowel", "along", "human", "wheel", "loose",
            "fifth", "fox", "acres", "shown", "lift", "thumb", "review", "weigh", "thirty", "system", "earn", "split",
            "wash", "bicycle", "writing", "knowledge", "forest", "condition", "bare", "location", "action", "coach",
            "species", "shade", "apple", "bus", "school", "twenty", "simple", "replied", "nose", "repeat", "sang",
            "direction", "facing", "fierce", "torn", "build", "freedom", "or", "carry", "chief", "took", "high",
            "habit", "greater", "minute", "community", "heavy", "college", "deal", "later", "herself", "floor", "pipe",
            "western", "were", "pilot", "act", "wheat", "no", "especially", "sea", "difficult", "consider", "mile",
            "discuss", "spend", "fallen", "you", "ear", "visitor", "chapter", "rice", "since", "jump", "discovery",
            "coat", "share", "too", "pot", "shot", "birthday", "sail", "state", "cup", "smooth", "definition",
            "opinion", "perfectly", "home", "grain", "luck", "place", "depth", "taught", "rhyme", "wide", "drop",
            "warn", "yesterday", "movie", "highway", "sides", "game", "needs", "create", "flies", "outer", "hurry",
            "regular", "tent", "value", "land", "jungle", "list", "accept", "buried", "song", "please", "page", "river",
            "however", "policeman", "lucky", "substance", "met", "organized", "had", "memory", "pie", "feature",
            "oldest", "straight", "customs", "divide", "jar", "least", "history", "only", "zero", "simplest", "lead",
            "positive", "sure", "month", "hardly", "rod", "look", "rich", "search", "fear", "will", "center",
            "particularly", "why", "whose", "age", "instrument", "trade", "pitch", "discover", "respect", "letter",
            "cool", "order", "held", "film", "concerned", "rock", "fun", "afternoon", "zoo", "different", "recent",
            "thin", "former", "bean", "hung", "moon", "happily", "locate", "shop", "load", "anywhere", "soft", "recall",
            "arrow", "form", "modern", "trouble", "driven", "bush", "plant", "settlers", "damage", "actual", "rate",
            "population", "wet", "first", "there", "contrast", "tall", "blank", "ought", "eat", "slabs", "aid",
            "soldier", "time", "instance", "solid", "comfortable", "may", "shirt", "our", "press", "bet", "proud",
            "snow", "mirror", "aboard", "sweet", "dirty", "flow", "dug", "last", "unhappy", "needle", "phrase",
            "joined", "still", "kill", "failed", "car", "rubber", "chamber", "pony", "reach", "society", "crowd",
            "curious", "feathers", "cent", "mix", "series", "appropriate", "cook", "doll", "stop", "willing", "silk",
            "can", "partly", "army", "full", "origin", "exactly", "for", "one", "crop", "frequently", "them", "box",
            "out", "alphabet", "thick", "entirely", "sat", "under", "element", "ahead", "worried", "limited", "court",
            "likely", "team", "screen", "famous", "church", "danger", "cabin", "column", "again", "burn", "prevent",
            "cotton", "written", "chicken", "space", "gently", "few", "wood", "spring", "skill", "bag", "part",
            "control", "wool", "pole", "gold", "brain", "chose", "scientist", "dig", "job", "low", "nine", "tropical",
            "natural", "good", "printed", "receive", "importance", "sight", "person", "wrong", "sleep", "graph", "ring",
            "growth", "as", "lonely", "sad", "seeing", "loss", "present", "men", "stems", "paid", "coal", "does",
            "throughout", "able", "sale", "ate", "beneath", "gun", "near", "been", "motion", "log", "religious",
            "engineer", "eleven", "grew", "courage", "red", "newspaper", "silent", "season", "but", "bottle", "wear",
            "angry", "window", "baby", "differ", "pink", "dollar", "theory", "find", "attack", "nearest", "mean",
            "putting", "seven", "object", "officer", "widely", "discussion", "which", "throat", "beautiful", "club",
            "hungry", "stream", "machinery", "farm", "becoming", "business", "half", "was", "mouse", "garden", "radio",
            "has", "pine", "fully", "into", "medicine", "across", "over", "threw", "cloud", "rocky", "cost",
            "vegetable", "blow", "morning", "solve", "vertical", "musical", "higher", "snake", "basic", "beauty",
            "carbon", "silver", "slightly", "expect", "syllable", "force", "struck", "free", "wore", "tone", "moment",
            "wherever", "selection", "buy", "sold", "never", "capital", "faster", "guard", "to", "life", "serve",
            "difficulty", "rabbit", "hair", "valuable", "relationship", "rubbed", "mission", "all", "noun", "chart",
            "it", "sort", "arm", "safety", "complete", "pig", "enjoy", "quite", "route", "gas", "inside", "bear",
            "hundred", "shorter", "successful", "cold", "sound", "choose", "then", "everybody", "sentence", "driver",
            "at", "slipped", "couple", "nest", "exact", "well", "introduced", "breathing", "start", "unusual", "green",
            "afraid", "situation", "sum", "avoid", "old", "evidence", "hat", "keep", "mighty", "leave", "construction",
            "salmon", "fog", "leather", "seldom", "special", "known", "composition", "cow", "duck", "mainly",
            "distance", "wise", "folks", "boat", "depend", "arrangement", "cage", "impossible", "property", "dropped",
            "lower", "piece", "tea", "shore", "industry", "bridge", "loud", "fly", "anybody", "once", "heat", "slip",
            "important", "off", "doctor", "above", "than", "bow", "easier", "your", "massage", "powerful", "before",
            "collect", "enter", "among", "son", "short", "bee", "onlinetools", "nice", "supply", "somebody", "large",
            "monkey", "military", "surface", "pencil", "flower", "hide", "grandfather", "traffic", "be", "duty", "gave",
            "shoulder", "journey", "cheese", "check", "book", "gentle", "this", "ship", "poem", "birds", "fell",
            "stove", "powder", "product", "iron", "care", "effort", "detail", "castle", "drive", "identity", "earlier",
            "let", "event", "clearly", "division", "offer", "meat", "cast", "tried", "foot", "what", "guess", "orange",
            "cell", "prize", "turn", "certain", "deep", "began", "corn", "fine", "size", "gravity", "equally",
            "ability", "brown", "fight", "muscle", "none", "grandmother", "foreign", "swimming", "dry", "bring", "lie",
            "smaller", "dinner", "ask", "rising", "applied", "matter", "show", "horn", "realize", "everywhere", "cloth",
            "beside", "push", "exciting", "gate", "stone", "case", "bread", "gift", "gain", "forth", "silly", "careful",
            "firm", "author", "father", "immediately", "anything", "giant", "changing", "given", "top", "service",
            "shape", "spite", "sheet", "made", "bit", "band", "little", "tune", "else", "nation", "people", "character",
            "someone", "wonderful", "block", "bark", "quiet", "battle", "caught", "rays", "finger", "atom", "she",
            "smile", "tree", "bad", "rocket", "year", "cause", "secret", "running", "stand", "listen", "using", "motor",
            "continent", "sick", "although", "handle", "fireplace", "class", "we", "typical", "his", "actually",
            "solar", "six", "water", "empty", "wind", "neck", "star", "if", "colony", "found", "row", "hunter", "write",
            "distant", "horse", "perhaps", "building", "mine", "term", "being", "sense", "indeed", "president", "park",
            "frighten", "hunt", "heading", "result", "earth", "private", "dull", "house", "lost", "cat", "occur",
            "mental", "border", "bigger", "until", "headed", "southern", "camp", "tomorrow", "broad", "talk", "problem",
            "chain", "guide", "football", "instant", "train", "most", "major", "decide", "second", "connected",
            "deeply", "select", "roar", "student", "public", "shelf", "office", "follow", "leaving", "automobile",
            "signal", "circle", "shallow", "thing", "sun", "scientific", "edge", "crew", "mother", "shut", "practice",
            "stood", "happened", "rather", "driving", "drawn", "surrounded", "thousand", "play", "south", "west",
            "behind", "upward", "pleasure", "date", "golden", "sets", "plane", "environment", "common", "adventure",
            "clean", "brief", "drove", "creature", "upper", "equal", "principal", "have", "cookies", "remarkable",
            "between", "do", "produce", "owner", "several", "manufacturing", "include", "label", "nature", "lesson",
            "essential", "cream", "hill", "straw", "laugh", "correctly", "weight", "wife", "strip", "attention",
            "gasoline", "winter", "struggle", "information", "weather", "choice", "hour", "treated", "bat", "jet",
            "ordinary", "plate", "hold", "favorite", "younger", "giving", "steady", "prove", "easily", "bell",
            "paragraph", "felt", "pound", "peace", "onto", "fresh", "combination", "chest", "fish", "particles",
            "child", "face", "roll", "speak", "eventually", "mistake", "middle", "camera", "told", "accurate",
            "himself", "occasionally", "whenever", "success", "use", "largest", "dream", "join", "drink", "base",
            "take", "swung", "real", "living", "thy", "lack", "thank", "paint", "mixture", "recently", "more",
            "chemical", "baseball", "remain", "planet", "replace", "greatly", "lose", "yourself", "am", "vast",
            "animal", "announced", "canal", "begun", "operation", "swing", "minerals", "think", "shoe", "myself",
            "round", "three", "easy", "almost", "diagram", "farther", "those", "word", "slight", "wrapped", "usual",
            "model", "degree", "ourselves", "tube", "naturally", "electricity", "spell", "nodded", "per", "swim",
            "previous", "station", "pure", "feel", "stronger", "tail", "pupil", "teacher", "add", "spoken", "upon",
            "shadow", "metal", "themselves", "aloud", "pour", "slept", "merely", "on", "studying", "parent", "getting",
            "mountain", "ranch", "account", "stopped", "gradually", "better", "because", "scene", "summer", "her",
            "kitchen", "white", "progress", "verb", "captured", "money", "should", "cowboy", "believed", "pattern",
            "board", "parallel", "symbol", "basis", "single", "win", "glass", "establish", "title", "end", "brush",
            "remember", "remove", "imagine", "whistle", "flag", "belt", "truck", "temperature", "east", "knife",
            "flight", "city", "worry", "bowl", "through", "yet", "early", "saw", "influence", "rhythm", "trick",
            "forty", "examine", "level", "story", "carefully", "gone", "mind", "studied", "send", "read", "could",
            "opportunity", "food", "excited", "mathematics", "square", "dress", "where", "breakfast", "bent", "task",
            "dear", "browserling", "consonant", "research", "rise", "piano", "shoot", "contain", "flew", "sugar",
            "lion", "after", "fur", "poor", "tip", "cake", "orbit", "arrange", "give", "nuts", "pack", "classroom",
            "grabbed", "sent", "tax", "any", "name", "further", "serious", "local", "ready", "blind", "floating",
            "know", "crack", "circus", "dangerous", "speed", "daily", "pull", "shout", "fastened", "soon", "subject",
            "package", "tobacco", "clay", "right", "try", "alive", "own", "steam", "smoke", "area", "example",
            "blanket", "trap", "gray", "except", "quick", "either", "close", "say", "save", "toy", "pond", "group",
            "escape", "each", "strange", "direct", "independent", "rest", "whale", "road", "pay", "north", "busy",
            "opposite", "language", "power", "function", "mice", "factor", "pretty", "youth", "tight", "proper",
            "outside", "swam", "organization", "ground", "develop", "calm", "ever", "anyone", "pleasant", "country",
            "mud", "some", "card", "desk", "layers", "finest", "doing", "best", "butter", "leader", "poetry", "answer",
            "yes", "deer", "got", "whole", "indicate", "party", "day", "exercise", "satellites", "run", "fellow",
            "hall", "pictured", "saddle", "vote", "report", "social", "though", "clothes", "such", "refer", "generally",
            "tears", "invented", "already", "done", "brass", "brick", "universe", "here", "extra", "dried",
            "protection", "speech", "tower", "increase", "thee", "television", "poet", "constantly", "grass",
            "practical", "science", "dish", "question", "fewer", "about", "cry", "pile", "popular", "bill", "are",
            "dozen", "measure", "audience", "mark", "want", "hearing", "suppose", "lying", "program", "away", "bank",
            "shall", "beyond", "pool", "climb", "note", "shells", "nobody", "wagon", "provide", "managed", "went",
            "doubt", "cover", "cattle", "knew", "break", "make", "additional", "die", "molecular", "when", "me",
            "possible", "useful", "magnet", "born", "slowly", "stretch", "therefore", "my", "health", "figure", "meant",
            "lunch", "itself", "branch", "hang", "tiny", "pride", "hay", "dust", "became", "body", "hand", "move",
            "everything", "labor", "happy", "hot", "change", "official", "strong", "instead", "salt", "with",
            "negative", "race", "alike", "black", "burst", "happen", "bite", "four", "ruler", "continued", "tongue",
            "plastic", "riding", "numeral", "cave", "conversation", "swept", "friend", "whether", "amount", "sharp",
            "young", "glad", "maybe", "he", "variety", "darkness", "picture", "support", "buffalo", "thought", "fairly",
            "left", "tales", "breath", "according", "hollow", "composed", "warm", "older", "store", "liquid", "air",
            "would", "jack", "tide", "mouth", "late", "five", "closer", "political", "quarter", "next", "within",
            "saved", "spread", "unit", "represent", "heard", "article", "way", "final", "principle", "today", "complex",
            "quickly", "wealth", "outline", "familiar", "score", "lake", "spent", "ants", "ran", "simply", "children",
            "oil", "century", "world", "idea", "soil", "mail", "master", "roof", "war", "bound", "pass", "stage",
            "position", "key", "equator", "certainly", "eight", "seat", "height", "electric", "unknown", "purpose",
            "explore", "fifteen", "built", "worker", "rope", "corner", "during", "surprise", "shake", "hospital",
            "taken", "two", "stay", "mostly", "shine", "point", "somehow", "equipment", "get", "attempt", "design",
            "watch", "blood", "yellow", "plus", "catch", "angle", "fair", "number", "raise", "underline", "lady",
            "probably", "blew", "improve", "strength", "allow", "leg", "walk", "hello", "copy", "funny", "reason",
            "egg", "fat", "trace", "national", "voice", "mysterious", "directly", "solution", "fruit", "come",
            "recognize", "worth", "pair", "frozen", "said", "neighborhood", "help", "making", "spin", "paper", "anyway",
            "behavior", "fort", "pick", "declared", "that", "farmer", "everyone", "kept", "material", "dirt", "energy",
            "means", "attached", "stranger", "mad", "member", "sheep", "brother", "strike", "average", "village",
            "welcome", "nails", "dot", "promised", "blue", "closely", "these", "government", "small", "trail", "police",
            "goose", "thus", "missing", "eager", "require", "grow", "elephant", "broke", "bone", "work", "kids",
            "queen", "count", "grade", "topic", "its", "mass", "door", "fence", "exist", "also", "soap", "structure",
            "toward", "refused", "having", "belong", "apartment", "great", "harbor", "income", "every", "hidden",
            "agree", "spirit", "eaten", "pain", "development", "eye", "root", "of", "library", "charge", "long",
            "explanation", "hurried", "whom", "addition", "while", "back", "experience", "tape", "truth", "joy",
            "related", "gather", "wonder", "hole", "suggest", "street", "front", "shelter", "education", "nothing",
            "garage", "telephone", "chance", "fall", "sometime", "satisfied", "rapidly", "unless", "observe",
            "furniture", "tell", "biggest", "effect", "line", "halfway", "law", "sitting", "parts", "sport", "stiff",
            "wave", "compound", "cap", "rough", "interior", "him", "cut", "meet", "against", "uncle", "vapor", "string",
            "fourth", "reader", "feet", "stuck", "sit", "like", "is", "death", "settle", "balloon", "airplane", "thou",
            "adult", "track", "broken", "plural", "badly", "dawn", "sell", "forget", "dead", "writer", "clothing",
            "many", "manner", "ten", "brave", "live", "experiment", "bright", "lay", "brought", "down", "setting",
            "chair", "sign", "waste", "nervous", "market", "slow", "potatoes", "herd", "combine", "frog", "steep",
            "third", "who", "silence", "wing", "wild", "tired", "noise", "huge", "softly", "town", "specific", "porch",
            "rose", "tie", "honor", "tightly", "exclaimed", "lips", "fact", "captain", "heart", "rain", "railroad",
            "diameter", "new", "copper", "nearby", "apart", "twelve", "pet", "wooden", "individual", "activity",
            "interest", "won", "open", "seems", "post", "somewhere", "see", "rule", "safe", "go", "bottom", "personal",
            "primitive", "learn", "coffee", "call", "fill", "raw", "double", "necessary", "native", "chosen", "total",
            "asleep", "type", "map", "sand", "room", "slave", "love", "available", "draw", "stepped", "beginning",
            "vessels", "women", "due", "wrote", "how", "path", "storm", "highest", "bar", "finish", "smallest", "pen",
            "correct", "friendly", "so", "become", "smell", "flat", "hurt", "mood", "till", "usually", "cannot", "led",
            "barn", "evening", "handsome", "fire", "daughter", "planning", "around", "another", "must", "enemy",
            "congress", "tribe", "image", "cutting", "dog", "standard", "prepare", "accident", "art", "below",
            "compass", "weak", "drew", "skin", "island", "dance", "plates", "family", "up", "news", "touch", "steel",
            "inch", "notice", "pressure", "future", "birth", "port", "price", "obtain", "meal", "seed", "by", "scared",
            "view", "advice", "clear", "lovely", "factory", "grown", "industrial", "possibly", "original", "ill",
            "ride", "thread", "tank", "wait", "step", "stairs", "past", "very", "mill", "method", "not", "forgot",
            "thrown", "basket", "sunlight", "greatest", "other", "excellent", "adjective", "plenty", "music", "range",
            "source", "process", "noon", "breathe", "finally", "fix", "magic", "main", "forgotten", "seen", "trip",
            "hit", "stick", "wolf", "production", "sink", "field", "light", "stock", "palace", "nearly", "movement",
            "disease", "company", "nor", "breeze", "just", "percent", "central", "tool", "slope", "wire", "tin",
            "section", "cross", "same", "travel", "climate", "larger", "coming", "passage", "ago", "longer", "ball",
            "stared", "purple", "pale", "stomach", "ice", "scale", "fed", "properly", "engine", "perfect", "globe",
            "balance", "plain", "explain", "fast", "general", "terrible", "test", "determine", "transportation", "week",
            "characteristic", "supper", "expression", "lamp", "nearer", "machine", "aside", "noted", "wish", "leaf",
            "affect", "fuel", "active", "taste", "something", "period", "claws", "ocean", "voyage", "curve", "union",
            "twice", "return", "laid", "understanding", "wall", "married", "throw", "boy", "dark", "rush", "current",
            "kind", "feed", "far", "valley", "without", "forward", "sister", "tonight", "bend", "visit", "difference",
            "shaking", "us", "describe", "might", "sing", "frame", "girl", "fighting", "sudden", "gulf", "record",
            "melted", "alone", "whatever", "needed", "including", "shinning", "atomic", "compare", "region", "pocket",
            "planned", "involved", "they", "sky", "excitement", "worse", "even", "disappear", "in", "desert",
            "exchange", "statement", "flame", "did", "moving", "length", "course", "plan", "quietly", "appearance",
            "slide", "goes", "oxygen", "suit", "physical", "lungs", "teach", "from", "teeth", "helpful", "arrive",
            "suddenly", "night", "fought", "yard", "clock", "carried", "put", "troops", "spider", "harder", "various",
            "entire", "triangle", "enough", "lot", "hard", "neighbor", "command", "atmosphere", "fifty", "rear", "man",
            "trunk", "ancient", "pan", "color", "now", "consist", "milk", "victory", "similar", "donkey", "whispered",
            "hope", "husband", "coast", "both", "came", "aware", "particular", "judge", "together", "citizen"
                                                                                                    "handsome",
            "hundred", "company", "whenever", "body", "butter", "industrial", "sport", "sent", "gun", "youth",
            "remember", "sum", "electric", "region", "bee", "unit", "for", "business", "heavy", "game", "sort",
            "against", "plenty", "flower", "hunter", "relationship", "frame", "ten", "grass", "service", "market",
            "rich", "rich", "keep", "finest", "harder", "discussion", "lost", "did", "command", "whispered", "oxygen",
            "wash", "joy", "front", "furniture", "various", "bush", "writer", "quickly", "girl", "younger", "customs",
            "worry", "front", "crowd", "medicine", "skin", "fed", "sick", "bee", "bark", "struggle", "fix", "seeing",
            "neck", "movement", "experience", "pig", "suit", "toward", "burn", "blind", "allow", "history", "press",
            "myself", "physical", "ran", "meal", "health", "camera", "doctor", "bound", "mirror", "molecular", "sent",
            "ten", "smell", "wore", "thumb", "shoulder", "as", "meant", "column", "action", "voice", "explain", "sail",
            "essential", "early", "mixture", "hunt", "straw", "join", "truth", "dish", "too", "east", "during", "hold",
            "badly", "after", "fallen", "journey", "printed", "noted", "pure", "alive", "refer", "taken", "strength",
            "race", "wing", "guard", "saved", "unhappy", "verb", "bag", "torn", "religious", "canal", "earth",
            "principal", "lady", "pair", "close", "hold", "suppose", "region", "plenty", "stove", "voice",
            "relationship", "potatoes", "range", "last", "small", "building", "park", "hurry", "eye", "proper", "power",
            "pretty", "announced", "morning", "hurry", "vote", "tried", "pale", "soon", "smoke", "handle", "nothing",
            "gasoline", "city", "slow", "deer", "torn", "guess", "younger", "earth", "star", "hall", "stick", "add",
            "stretch", "took", "sat", "sides", "place", "health", "play", "score", "mainly", "better", "fence", "good",
            "crop", "disappear", "yourself", "stopped", "them", "travel", "plan", "noun", "fuel", "avoid", "leather",
            "sat", "wear", "until", "southern", "quick", "oldest", "loss", "close", "object", "entire", "feathers",
            "troops", "due", "afternoon", "bark", "you", "process", "letter", "student", "engineer", "today",
            "according", "welcome", "born", "equally", "tropical", "ride", "purple", "market", "silly", "dinner",
            "police", "drink", "cabin", "lonely", "four", "red", "drink", "account", "replace", "fight", "missing",
            "oil", "ten", "asleep", "ahead", "somehow", "effect", "balloon", "activity", "still", "clothes", "equator",
            "may", "subject", "girl", "instrument", "even", "vote", "instead", "harbor", "within", "spin", "parts",
            "under", "cheese", "manufacturing", "herself", "coach", "height", "protection", "arrange", "silence",
            "give", "climb", "bite", "silent", "studied", "helpful", "necessary", "lucky", "police", "engine", "bottom",
            "mix", "adult", "fight", "size", "away", "salt", "whispered", "brush", "customs", "onlinetools", "chemical",
            "compass", "flower", "total", "stop", "hit", "unknown", "fighting", "handle", "rain", "coast", "became",
            "flame", "rays", "enjoy", "it", "freedom", "run", "pile", "wherever", "beginning", "cloth", "pine",
            "floating", "straight", "however", "got", "end", "happy", "thirty", "cause", "managed", "queen", "quiet",
            "post", "atmosphere", "began", "full", "hall", "bat", "lovely", "represent", "blood", "fresh", "success",
            "back", "sheep", "caught", "together", "composed", "carbon", "adjective", "prepare", "blood", "pleasure",
            "eventually", "western", "grass", "exciting", "willing", "burn", "aside", "increase", "paint", "attention",
            "potatoes", "piano", "ride", "fog", "hour", "piano", "writer", "tonight", "around", "price", "element",
            "done", "needle", "circus", "depend", "review", "rather", "lift", "dozen", "gasoline", "expression",
            "early", "once", "silk", "blew", "mark", "hurt", "drew", "being", "folks", "game", "tail", "pig", "today",
            "beginning", "foreign", "art", "together", "subject", "till", "husband", "cool", "recognize", "southern",
            "instead", "neighborhood", "taste", "funny", "door", "recent", "occur", "green", "wrong", "soft", "prize",
            "sand", "lucky", "late", "raise", "people", "pain", "silent", "determine", "protection", "animal", "white",
            "led", "avoid", "both", "that", "general", "nearest", "heard", "finest", "low", "as", "climate", "clearly",
            "individual", "double", "metal", "compare", "happened", "range", "disappear", "without", "loud", "frighten",
            "policeman", "world", "you", "am", "trunk", "swimming", "bare", "ship", "hold", "round", "not", "seldom",
            "bent", "surrounded", "hang", "main", "might", "drink", "behind", "thou", "reader", "rapidly", "diameter",
            "swam", "area", "lot", "spirit", "throat", "careful", "east", "storm", "he", "excited", "field", "west",
            "bet", "close", "copy", "simply", "share", "library", "mine", "catch", "slabs", "adventure", "mud", "horse",
            "feathers", "dog", "belt", "garden", "whispered", "anyway", "merely", "related", "middle", "yes",
            "composed", "door", "managed", "bank", "principal", "necessary", "dig", "morning", "kids", "four", "occur",
            "brown", "shut", "noise", "planning", "door", "slow", "thumb", "community", "or", "writing", "colony",
            "she", "finish", "accurate", "nice", "add", "change", "wing", "rush", "warn", "clean", "death", "poetry",
            "word", "discuss", "start", "tomorrow", "way", "son", "lamp", "grabbed", "outside", "arm", "notice",
            "prevent", "together", "soon", "raw", "mine", "grandfather", "mix", "drawn", "return", "throughout",
            "hundred", "bill", "belong", "modern", "band", "strong", "sea", "effect", "beat", "than", "day", "syllable",
            "thought", "shot", "master", "harder", "mail", "tone", "hole", "stiff", "nearly", "section", "trail",
            "sport", "read", "eventually", "castle", "having", "conversation", "observe", "feature", "mistake",
            "energy", "plus", "pleasant", "feel", "question", "describe", "familiar", "door", "swung", "whenever",
            "where", "equally", "cold", "long", "two", "tune", "follow", "temperature", "milk", "secret", "label",
            "able", "stepped", "taken", "bus", "someone", "income", "clean", "beside", "fence", "minerals", "wonder",
            "receive", "real", "crew", "policeman", "sail", "battle", "will", "rich", "every", "studying", "handsome",
            "group", "troops", "total", "plenty", "mother", "sound", "basis", "is", "play", "breath", "successful",
            "spell", "union", "society", "ahead", "flew", "through", "country", "order", "valuable", "north", "bell",
            "time", "beneath", "principal", "lie", "business", "police", "smooth", "molecular", "any", "difference",
            "half", "castle", "careful", "met", "pattern", "stairs", "ran", "bow", "joined", "mad", "tomorrow",
            "opposite", "loud", "construction", "nodded", "pick", "burst", "especially", "arrive", "fruit", "fairly",
            "production", "case", "body", "stick", "friendly", "met", "origin", "courage", "owner", "thin", "later",
            "page", "master", "nearly", "involved", "sides", "principle", "scientific", "form", "arm", "dirty", "next",
            "queen", "lake", "nuts", "detail", "clay", "by", "community", "finish", "electricity", "present", "swing",
            "small", "carried", "none", "wise", "party", "machine", "education", "water", "tried", "them", "pile",
            "last", "top", "impossible", "sheep", "baseball", "select", "rich", "furniture", "giant", "not", "circus",
            "gradually", "stock", "onlinetools", "warn", "basic", "center", "return", "cover", "ancient", "away",
            "improve", "chart", "mouth", "including", "say", "long", "compound", "mistake", "available", "round",
            "famous", "step", "sit", "wonder", "disappear", "slightly", "worker", "courage", "crack", "final", "game",
            "necessary", "fireplace", "those", "eat", "screen", "deer", "hill", "zero", "against", "dozen", "page",
            "block", "porch", "like", "couple", "differ", "compound", "wind", "test", "longer", "nest", "chapter",
            "fox", "hello", "equipment", "vegetable", "rose", "equally", "proud", "negative", "settle", "list",
            "vertical", "observe", "mean", "selection", "might", "gradually", "stared", "citizen", "automobile",
            "possible", "closer", "tales", "signal", "film", "route", "round", "trap", "feature", "duty", "pine",
            "nuts", "declared", "there", "rock", "specific", "needle", "stock", "support", "field", "your", "influence",
            "saved", "mud", "like", "hardly", "wash", "cause", "quiet", "fall", "five", "thousand", "thrown",
            "favorite", "fuel", "sentence", "tax", "accurate", "gather", "wall", "club", "steam", "tight", "nearby",
            "trip", "led", "terrible", "win", "taught", "forward", "nails", "reach", "exercise", "trouble", "farmer",
            "cutting", "yet", "separate", "also", "coffee", "drive", "harder", "possibly", "slept", "vast", "repeat",
            "slowly", "equipment", "band", "flag", "pocket", "shore", "writing", "drop", "exchange", "driver",
            "distant", "mile", "indicate", "compass", "copper", "space", "brown", "told", "brass", "memory", "team",
            "giving", "afraid", "principle", "season", "season", "extra", "forest", "necessary", "typical", "another",
            "kept", "gasoline", "learn", "floating", "vapor", "excellent", "entire", "line", "boy", "seems", "story",
            "soft", "unit", "clean", "continent", "building", "correctly", "danger", "mad", "keep", "angry",
            "eventually", "manufacturing", "yard", "part", "present", "came", "contain", "track", "trouble", "strike",
            "funny", "leather", "poem", "cowboy", "rich", "discover", "stiff", "bean", "dawn", "desk", "birth", "crowd",
            "led", "mud", "case", "together", "nuts", "stove", "tribe", "write", "steady", "jack", "cry", "mouse",
            "rule", "kind", "burn", "slipped", "direction", "drove", "income", "stage", "bill", "pool", "cold",
            "beyond", "magnet", "tower", "fed", "buy", "station", "natural", "negative", "return", "breakfast",
            "tonight", "major", "child", "silver", "driving", "stage", "frequently", "post", "race", "although", "skin",
            "needs", "column", "row", "over", "salmon", "fireplace", "section", "machine", "answer", "are", "try",
            "group", "court", "one", "foreign", "telephone", "new", "wrong", "grandfather", "slide", "weight", "plan",
            "picture", "finest", "nearest", "shout", "recall", "because", "table", "principal", "orange", "president",
            "lady", "century", "thee", "under", "act", "industry", "slipped", "replace", "union", "warm", "income",
            "shut", "truth", "actually", "using", "vowel", "gray", "shut", "blood", "merely", "thick", "author",
            "essential", "shorter", "saddle", "protection", "gasoline", "stomach", "basis", "twelve", "scared",
            "quarter", "warn", "discuss", "according", "typical", "gas", "stood", "strip", "actual", "total",
            "perfectly", "paragraph", "begun", "spell", "evening", "plenty", "way", "outer", "fast", "brick", "bridge",
            "capital", "jar", "barn", "pot", "mysterious", "end", "bring", "welcome", "part", "total", "shine", "sure",
            "therefore", "imagine", "why", "steam", "bark", "made", "fall", "remain", "newspaper", "species", "chose",
            "case", "variety", "captured", "afternoon", "means", "social", "vote", "every", "pattern", "center",
            "chemical", "nearer", "almost", "pot", "orange", "tube", "mile", "tomorrow", "fur", "alphabet", "newspaper",
            "section", "town", "trick", "trade", "till", "natural", "waste", "log", "must", "tower", "lay", "roof",
            "almost", "onlinetools", "be", "everybody", "union", "faster", "orange", "browserling", "swung", "tree",
            "union", "original", "you", "review", "already", "ordinary", "orbit", "take", "habit", "flow", "education",
            "post", "believed", "stomach", "attached", "steam", "them", "sugar", "roof", "lion", "wool", "rice", "cast",
            "stared", "tongue", "doubt", "felt", "room", "whistle", "done", "phrase", "refused", "review", "straw",
            "people", "firm", "easy", "north", "during", "stranger", "thread", "down", "river", "quickly", "determine",
            "making", "operation", "shake", "smell", "worker", "flow", "difficult", "western", "produce", "shaking",
            "pack", "floor", "hunt", "roar", "inch", "village", "slow", "tool", "national", "truth", "pole", "knew",
            "split", "apartment", "spite", "blow", "map", "thee", "nearer", "west", "pour", "gather", "tired", "peace",
            "widely", "neighbor", "correct", "name", "recently", "gray", "available", "measure", "table", "wonderful",
            "comfortable", "board", "meant", "mud", "several", "rocky", "design", "satellites", "plant", "tiny",
            "paper", "thirty", "police", "score", "prevent", "enjoy", "finest", "length", "got", "wrapped", "universe",
            "command", "trick", "kept", "gone", "phrase", "steel", "kitchen", "variety", "shape", "prove", "fire",
            "traffic", "student", "ring", "say", "does", "live", "shorter", "storm", "shelter", "image", "solve",
            "planet", "bigger", "hospital", "kitchen", "fireplace", "hard", "day", "powerful", "syllable", "caught",
            "seems", "select", "printed", "gun", "longer", "he", "powerful", "green", "lion", "opportunity", "pie",
            "classroom", "flat", "me", "day", "her", "fairly", "heart", "discovery", "provide", "possible",
            "additional", "graph", "happened", "slight", "war", "back", "hit", "thread", "what", "per", "cream", "bad",
            "corner", "danger", "voice", "climb", "atom", "thread", "certainly", "exercise", "earlier", "material",
            "lost", "everything", "brother", "properly", "previous", "president", "pocket", "larger", "most", "pale",
            "usually", "sharp", "window", "bottle", "most", "girl", "join", "beyond", "able", "pilot", "worry", "empty",
            "whispered", "find", "fairly", "understanding", "divide", "circle", "attention", "term", "title", "ten",
            "government", "constantly", "corn", "jump", "small", "scared", "cloth", "last", "or", "struggle", "early",
            "adult", "poor", "want", "shells", "melted", "curious", "before", "rope", "hot", "writer", "pencil", "poor",
            "loud", "sister", "addition", "is", "sentence", "apple", "birth", "blank", "avoid", "coffee", "rough",
            "for", "species", "struck", "master", "aboard", "needs", "wash", "chart", "cup", "distance", "had", "lady",
            "maybe", "nearer", "pile", "brick", "lips", "sell", "chicken", "box", "victory", "street", "explore",
            "single", "by", "escape", "cast", "away", "storm", "water", "neighbor", "dawn", "porch", "company",
            "silver", "basket", "smell", "beautiful", "surrounded", "planet", "grass", "die", "name", "within",
            "typical", "coast", "enough", "mouse", "muscle", "mistake", "barn", "swung", "mud", "enemy", "bottle",
            "dollar", "local", "lonely", "close", "national", "great", "mysterious", "vessels", "bow", "nothing",
            "weigh", "shoe", "stage", "bigger", "hay", "taught", "future", "surface", "hung", "burst", "graph", "low",
            "queen", "home", "notice", "basis", "struggle", "till", "sport", "square", "pile", "crop", "handsome",
            "morning", "ten", "hunter", "mental", "children", "hollow", "live", "complex", "setting", "son", "sum",
            "poet", "explanation", "pig", "young", "locate", "opinion", "care", "poet", "fireplace", "hill", "addition",
            "crop", "father", "plate", "wave", "why", "town", "on", "language", "became", "pressure", "research", "so",
            "soil", "charge", "tropical", "test", "thin", "through", "cheese", "rocky", "nice", "replied", "spoken",
            "eager", "add", "chose", "dozen", "needle", "already", "nobody", "ten", "salt", "chain", "football",
            "because", "opportunity", "broken", "inside", "take", "task", "told", "fuel", "planet", "including",
            "discussion", "swung", "dress", "pleasant", "gradually", "that", "size", "became", "state", "consonant",
            "brick", "vessels", "everything", "shorter", "settle", "yard", "bound", "twelve", "strong", "using", "leaf",
            "twelve", "scientific", "came", "drew", "wood", "check", "setting", "fairly", "solve", "strange", "yes",
            "ranch", "river", "write", "printed", "root", "tube", "strong", "ring", "before", "plenty", "map", "cannot",
            "rush", "something", "previous", "valley", "collect", "water", "root", "of", "place", "dust", "birds",
            "machinery", "wire", "doctor", "rule", "light", "although", "wash", "modern", "addition", "pile", "wave",
            "bear", "turn", "choice", "report", "hunt", "camera", "complex", "pressure", "screen", "evidence",
            "collect", "basic", "handsome", "greatest", "bigger", "point", "pound", "unless", "direction", "frame",
            "scale", "mental", "manner", "cook", "graph", "swimming", "weight", "material", "white", "rock", "feathers",
            "pick", "guard", "military", "remember", "dish", "yet", "morning", "fell", "audience", "atom", "jar",
            "sometime", "after", "inch", "depend", "pen", "familiar", "hidden", "running", "ring", "about", "step",
            "older", "surprise", "yellow", "report", "atomic", "hurt", "forgot", "happy", "leg", "actually", "wave",
            "hollow", "deal", "religious", "shaking", "roll", "put", "nearly", "garage", "excited", "lying", "swing",
            "well", "offer", "habit", "saddle", "deep", "student", "snow", "ants", "pound", "respect", "silver",
            "silent", "whispered", "twice", "missing", "off", "steady", "advice", "physical", "farm", "real", "army",
            "apart", "running", "thin", "improve", "back", "thought", "collect", "mighty", "negative", "salt", "chain",
            "creature", "police", "claws", "active", "running", "story", "clay", "experiment", "square", "chicken",
            "taste", "extra", "your", "paper", "guide", "speak", "becoming", "country", "sang", "above", "sell",
            "porch", "raw", "possible", "alone", "he", "or", "bottle", "numeral", "nails", "equipment", "depth",
            "although", "look", "touch", "production", "back", "moving", "second", "cutting", "attack", "difficult",
            "few", "happen", "voyage", "key", "replied", "nobody", "me", "horse", "quickly", "popular", "expect",
            "task", "instant", "electricity", "warm", "new", "its", "willing", "figure", "yourself", "tax", "butter",
            "stand", "me", "drew", "fill", "ask", "muscle", "spread", "herd", "flat", "obtain", "way", "tomorrow",
            "mud", "bat", "darkness", "chosen", "specific", "heading", "so", "save", "stems", "rising", "lying",
            "package", "business", "snow", "leg", "lungs", "increase", "send", "handle", "substance", "pleasure",
            "even", "further", "becoming", "frighten", "hungry", "does", "took", "we", "pupil", "state", "lady", "six",
            "spider", "along", "sides", "element", "dry", "would", "important", "huge", "neck", "torn", "aware", "race",
            "enjoy", "promised", "liquid", "cream", "ten", "sunlight", "brave", "hot", "cloud", "nor", "primitive",
            "prevent", "radio", "birthday", "him", "answer", "notice", "chapter", "protection", "seven", "circus",
            "dropped", "leaf", "success", "leaving", "fuel", "middle", "trap", "ill", "yellow", "while", "brother",
            "saw", "west", "giant", "basis", "seldom", "onto", "never", "voyage", "hospital", "hit", "aside", "flat",
            "condition", "safe", "room", "barn", "adjective", "blow", "heading", "foot", "grandmother", "per", "lead",
            "chosen", "cool", "zero", "huge", "vegetable", "facing", "basis", "about", "parent", "find", "mine", "type",
            "record", "due", "desert", "see", "none", "truth", "swam", "child", "vapor", "climate", "best", "rule",
            "tales", "progress", "sentence", "truth", "lucky", "plenty", "before", "worker", "here", "nature",
            "everywhere", "exciting", "act", "gasoline", "command", "straight", "dinner", "perfectly", "constantly",
            "give", "deep", "seems", "train"]

print("phil: {}".format(philly))
print("ted: {}".format(ted))
print("bin: {}".format(bin))
print("o5a: {}".format(o5a))
print("guip: {}".format(gui))

philly = Phillyclause89_comma_and(spam1000)
ted = TedTheTwonk_comma_and(spam1000)
bin = Binary101010_comma_and(spam1000)
o5a = o5a_comma_and(spam1000)
gui = guipalazzo_comma_and(spam1000)
